### ISSUE TITLE
25: Expand testing chapter

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#176]
## Location within the Book

* Chapter or Appendix: 25 Introducing Tests
* Section:
* Subsection:

## Description 

IMHO this chapter would benefit from adding more background information into it.

## Possible Solutions

Briefly explain what unit, integration and functional tests are.

Explain `unittest` vs `pytest`. Pros and cons.

Django documentation use the `TestCase` and `SimpleTestCase` classes for writing tests:
<https://docs.djangoproject.com/en/3.0/topics/testing/overview/>
They should be mentioned, and the advantages of using a different approach explained.

It should be better explained what `pytest.mark` is, and why we need it.

I think all this would help to prevent the reader from feeling lost or confused.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
