### ISSUE TITLE
Explain static files

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#193]
## Description 

There is no info whatsoever on static files: images, stylesheets, etc.

## Possible Solutions

Add a chapter explaining how to deal with static files, both while developing (debug activated) and in production.

Some screenshots, such as figure 45, show a cheese image in the navbar, which could be used to explain this subject.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
