### ISSUE TITLE
Explain DeleteView

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#194]
## Description 

The book explains `ListView`, `DetailView`, `CreateView` and `UpdateView`.

In order to have a full **CRUD**, `DeleteView` should be explained as well.

## Possible Solutions

Add a 'Delete cheese' feature to Everycheese.

**Comment by littlag** [comment]
a

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
