### ISSUE TITLE
Minor inconsistency in description 17.1.3

### ISSUE THREAD

**Issue by The-Judge** [feldroy/django-crash-course#195]
## Location within the Book

* Chapter: 17.1.3

## Description 

In the book it reads `ADMINS = [("Your name here", "your-name-here@example.com")]`; in your GH sources (and so, in the result of what the user sees), the first tuple element is in `""" """` - section-notation.

## Possible Solutions

I'd suggest to either make it appear 1:1 in the book or, if there is a good reason to have it in section comment, explain why this is.

**Comment by pydanny** [comment]
This was an issue with django-crash-starter which we just resolved. Thank you!
