### ISSUE TITLE
DATABASES setup incomplete

### ISSUE THREAD

**Issue by The-Judge** [feldroy/django-crash-course#197]
## Location within the Book

* Chapter: 18.4.1

## Description 

You show how to learn the name of the PostgreSQL DB from the `base.py` settings, but don't explain what to do if the local DB setup requires credentials or if a non-local DB server is used.

And that isn't the only issue with this:
The comments in the GH code and the book both quote:

> # Raises ImproperlyConfigured Exception if DATABASE_URL Not in os.environ

And exactly that happens when executing `python manage.py migrate` in 18.7 .
No idea how a beginner should untangle this on their own since this is even spiced with non-basic configuration concepts of your cookiecutter - template.

Currently, this puts a full stop to every beginners process with the book.

## Possible Solutions

Mention this, at least, and refer to [Djangos Database setup instructions](https://docs.djangoproject.com/en/3.0/ref/settings/#databases).
Also, provide additional details what to do with `DATABASE_URL` EnvVar to make it work.

**Comment by EmilGorniak** [comment]
I ran into this particular problem. I am the beginner and I couldn't carry out the migration as it is written in the book.  This is what I've got:

` conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: fe_sendauth: no password supplied
`
I resolved this temporarily following the django documentation by putting the following code instead:

`DATABASES = {
    # Raises ImproperlyConfigured Exception
    # if DATABASE_URL Not in os.environ
    # "default": env.db(
    #     "DATABASE_URL", default="postgres:///everycheese"
    # )

    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'everycheese',
        'USER': 'postgres',
        'PASSWORD': 'mypassword',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}`

But now, I have no idea whether I did sth good or bad, which in turn may affect other functionalities.

**Comment by luzfcb** [comment]
@EmilGorniak Thanks for the comment. What operating system are you using?

**Comment by EmilGorniak** [comment]
@luzfcb, Windows 10.

**Comment by paultis** [comment]
I'm also on Windows 10, seeing the same error as @EmilGorniak   

```
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: fe_sendauth: no password supplied
```

Perhaps it is related to how I created the database?  In the everycheese conda environment the command

`createdb everycheese `

failed with 

`createdb: error: could not connect to database template1: FATAL:  password authentication failed for user "paultis"`

even after I went into psql and ran 

`CREATE ROLE paultis WITH CREATEDB LOGIN;`

So I went to pgAdmin and set the password for paultis user, and then was able to create the database.

**Comment by paultis** [comment]
@luzfcb This worked for me - perhaps adding the following couple of lines to the documentation would help others?

In the conda environment, I set the DATABASE_URL environmental variable using the format

`postgres://{user}:{password}@{hostname}:{port}/{database-name}`

as follows

`set DATABASE_URL=postgres://postgres:mypassword@localhost:5432/everycheese`

then I was able to run the migrations on the db.   I'm guessing we're expected to set the password in this way to avoid putting it in a file.

**Comment by technichor** [comment]
Another beginner here. This is the documentation that helped me through this missing step.
[https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html]

**Comment by paultis** [comment]
Thanks @technichor that answered the question for me.  This is my first time using cookiecutter.

**Comment by pydanny** [comment]
Windows users we are asking to move to SQLite. Sorry, as Microsoft and EnterpriseDB aren't officially supporting PostgreSQL on Windows, neither can we. It's taking away our time from getting this book to final status and into print format.

Our plan is to eventually move all Windows users to WSL2 as that stabilizes and matures in the months to come.

**Comment by contadorpl** [comment]
i have lost a whole day on this, why don't you create user first and then database?

**Comment by contadorpl** [comment]
(everycheese) C:\Users\Splendor\everycheese>createdb
Password:
Password:
createdb: error: could not connect to database template1: KATASTROFALNY:  autoryzacja hasłem nie powiodła się dla użytkownika "Splendor"

what should i do now? :-)

**Comment by contadorpl** [comment]
> Windows users we are asking to move to SQLite. Sorry, as Microsoft and EnterpriseDB aren't officially supporting PostgreSQL on Windows, neither can we. It's taking away our time from getting this book to final status and into print format.
> 
> Our plan is to eventually move all Windows users to WSL2 as that stabilizes and matures in the months to come.

people are still fighting with this and nobody help them

**Comment by pydanny** [comment]
Closing this as the answer on Windows is to move to SQLite until further notice. Not continue trying something we are advising against.
