### ISSUE TITLE
Add final test run before final commit

### ISSUE THREAD

**Issue by GarretL** [feldroy/django-crash-course#200]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Chapter or Appendix: 56
* Section: 5 - Commit the Changes
* Subsection: 

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

Add a final run of the tests before the final commit.

Great book, really enjoyed it!

**Comment by pydanny** [comment]
🚢 🧀 

Can you provide your full name so we can credit you properly in the book?
