### ISSUE TITLE
Provide rationale for why we should include __init__.py if using Python 3.

### ISSUE THREAD

**Issue by kimrob** [feldroy/django-crash-course#202]
# Location within the Book

* Chapter or Appendix: II Everycheese
* Section: 29
* Subsection: 2

## Description 

> Note: even though __init__.py is optional on Python 3, create it anyway.

## Possible Solutions

This line is tossed at the end of the section without a justification as to why the reader should keep this practice. I don't know the *why* though. Is this to preserve any backwards compatibility with modules that may still be running Python 2?

**Comment by pydanny** [comment]
Thanks for the catch! This new text should clear things up:

> ote: even though `__init__.py` is technically optional on Python 3, create it anyway. By including the `__init__.py`, it empowers us to use relative imports in our tests.

**Comment by pydanny** [comment]
🚢 🧀
