### ISSUE TITLE
49.3: Git Commit Message Text Overflow

### ISSUE THREAD

**Issue by realcooltrev** [feldroy/django-crash-course#204]
## Location within the Book

* Chapter or Appendix: 49
* Section: 3
* Subsection: 0

## Description 

For the git commit message written below, the text overflows past the gray code box by two characters (at least in the .pdf):

`git commit -m "Add creator field to Cheese.model and custom migratio`n"

## Possible Solutions

The git commit message text in this section should be modified so that it fits in the gray box in this section of the .pdf:

`git commit -m "Add creator field to Cheese.model and custom migration"`

**Comment by pydanny** [comment]
🚢 🧀
