### ISSUE TITLE
51.7: Git Commit Message Text Overflow

### ISSUE THREAD

**Issue by realcooltrev** [feldroy/django-crash-course#205]
## Location within the Book

* Chapter or Appendix: 51
* Section: 7
* Subsection: 0

## Description 

For the git commit message written below, the text overflows past the gray code box by one character (at least in the .pdf):

`git commit -m "Modify cheese factory to create a cheese creator user`"

## Possible Solutions

The git commit message text in this section should be modified so that it fits in the gray box in this section of the .pdf:

`git commit -m "Modify cheese factory to create a cheese creator user"`

**Comment by pydanny** [comment]
:ship: 🧀
