### ISSUE TITLE
Explain how to upload files

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#207]
## Description 

Uploading files is a basic feature commonly required in many apps.

## Possible Solutions

Implement and explain how to upload a photo for each cheese.

**Comment by pydanny** [comment]
This is in a planned extension. ;-)

**Comment by quique** [comment]
Alright!

Then I'd suggest adding it to [What's up with the extensions?](https://www.feldroy.com/collections/two-scoops-press/products/django-crash-course#extensions)

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
