### ISSUE TITLE
Explain internationalization and localization

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#209]
## Description 

i18n/l10n is a basic feature required by any website with a global audience.

## Possible Solutions

Make Everycheese available in a different language, such as Chinese or Spanish.

**Comment by pydanny** [comment]
We're probably going to start with Portuguese and Spanish. Our own @luzfcb is a native Portuguese speaker and all of us at @royfeld have some capability with Spanish.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
