### ISSUE TITLE
Update the cover

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#210]
## Location within the Book

* Chapter or Appendix: Cover page
* Section: 
* Subsection:

## Description 

The cover page show the authors as Daniel Roy Greenfeld and Audrey Roy Greenfeld.

## Possible Solutions

Modify the cover so that it sports your new family name: Daniel Feldroy and Audrey Feldroy.

**Comment by pydanny** [comment]
This got resolved a while ago. 😉
