### ISSUE TITLE
16: Spurious {Sample}

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#211]
## Location within the Book

* Chapter or Appendix: 16 Using Cookiecutter and Template
* Section:
* Subsection:

## Description 

> The first tool we install into our projects is **Cookiecutter**, which we’ll be using in future extensions and books. {Sample}

I don't know if that _{Sample}_ is a markup error, or if it is some kind of unlabelled TODO.

## Possible Solutions

Fix or remove that.

**Comment by pydanny** [comment]
Removed!
