### ISSUE TITLE
35.3: Explain template_name

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#213]
## Location within the Book

* Chapter or Appendix:
* Section: 35.3 See the View in Action
* Subsection:

## Possible Solutions

Explain that, by default, `ListView` uses `<model_name>_list.html`, but that we can choose a different filename setting up `template_name` in the view.

In section 37.2,  explain that, by default, `DetailView` uses `<model_name>_detail.html`, but that we can choose a different filename setting up `template_name` in the view.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
