### ISSUE TITLE
36.2 Explain context_object_name

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#214]
## Location within the Book

* Chapter or Appendix:
* Section: 36.2 Fill in the Template
* Subsection:

## Possible Solutions

Explain we can use `context_object_name` in the view to give it a more descriptive name.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
