### ISSUE TITLE
36.2 Further explain the `for` template tag

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#215]
## Location within the Book

* Chapter or Appendix:
* Section: 36.2 Fill in the Template
* Subsection:

## Possible Solutions

Mention that, inside the loop, the `forloop` template variable has attributes such as `counter` `counter0`, `first`, `last`, `parentloop`, `revcounter`, etc that can come in handy.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
