### ISSUE TITLE
Explain Admin Customization

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#216]
## Possible Solutions

Explain how to change the looks and behaviour of the Admin:

* How to override default admin templates
* `AdminSite` attributes
* `ModelAdmin` and its attributes: `fields`, `fieldsets`, `inlines` (`StackedInline`, `TabularInline`)
* How to create a filter sidebar and a search box
* How to grant a user access to only a subset of the admin features.

(I guess you'll want to do it in a future extension.)

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
