### ISSUE TITLE
References to python 3.7 should be explained

### ISSUE THREAD

**Issue by lmsteffan** [feldroy/django-crash-course#218]
While your book is stated to work with Python3.8, it gives instructions for the installation of Python3.7 (through Anaconda), which could be confusing.

##  Location within the Book

* Chapter or Appendix: The ultimate Django setup
* Section: 1.5 Installing Conda
* Subsection: 1.5.1, 1.5.2, 1.5.3.

## Description 

There are three references to Python 3.7 in the subsections about installing Conda.

## Possible Solutions

Add some explanation like 
"The standard Conda downloads will install Python 3.7, but we'll see later on (in 3.2 Setup a new Conda environment) how we can very easily use Python 3.8".

**Comment by pydanny** [comment]
🚢 🧀
