### ISSUE TITLE
Typo : Missing closing parenthesis

### ISSUE THREAD

**Issue by lmsteffan** [feldroy/django-crash-course#219]
## Location within the Book

* Chapter or Appendix: 42
* Section: 6 
* Subsection: second item in the enumeration

## Description 
Typo : "str(cheese is equal"

## Possible Solutions
add a closing parentheses after "cheese" :-D

**Comment by Scarletbegonias68** [comment]
We just corrected this typo. Thank you @lmsteffan for submitting it! We will be giving attribution in the next update of the book :smile: 
🚢 🧀
