### ISSUE TITLE
Add audio version

### ISSUE THREAD

**Issue by pydanny** [feldroy/django-crash-course#22]
## Description 

For people who like to listen to books! Not sure we'll do it, but it might be a good idea. 😄 

Suggested by Kamanzi Franchesco.

**Comment by deeprave** [comment]
While a neat idea, just now sure how practical it would be given the "code along" style.
I'm a big fan and consumer of audiobooks, but rarely on books with technical content.

**Comment by mattwinslow** [comment]
Agree with @deeprave....

Perhaps there's an opportunity to create a video series of the content (and additional series/courses/packs for future extensions) that could include a mix of slides(?) and follow-along screencasts?

Something similar to the format/presentation of Jeffrey Way's [Laracasts](https://laracasts.com/). 

Having said that, video would be a **huge** undertaking, and as a consumer I'd expect to be charged (and willing to pay) a premium for it.

Especially for the content in this Crash Course (although, I am extremely anxious to devour your content around Vue.js), it seems as though video may be a great medium that could bridge the gap between "telling" and "hand-holding".

Of course....insert all sorts of disclaimers here....this approach didn't _seem_ to work for sites like [GoDjango](https://godjango.com/).

**Comment by pydanny** [comment]
Here's the thing: if we record an audio or video version of this book, we won't have time to do Two Scoops of Django 3.x. Or work on a number of other books and projects, including for COVID-19 related items.

**Comment by mattwinslow** [comment]
Right...audio/video would be a large undertaking.

Nix it or at least back burner it until you've gotten through the rest of your book/content TODO.

Seems like Two Scoops of Django for 3.x. and the additional content modules should net more revenue than any bump from audio or video for this book anyhow, so makes most financial sense for y'all to focus on those...

**Comment by pydanny** [comment]
I think we want to just do print. That's our specialty.
