### ISSUE TITLE
No explanation for makemigrations

### ISSUE THREAD

**Issue by lmsteffan** [feldroy/django-crash-course#220]
## Location within the Book

* Chapter or Appendix: 23
* Section: 2
* Subsection:

## Description 

You state "Then make and apply our migrations as usual", but this is the first time that you mention the command ```makemigrations```. For that matter, the concept of migrations in Django is not wholly explained anywhere.

## Possible Solutions

Add a paragraph "What are migrations ?

Whenever we do something that affects the structure of the database (mostly when we modify models, but also when we create the database), we need to apply these changes : that's called a migration. We do it in two steps :
- first we create the commands that will change the database
```python manage.py makemigrations```
- then we apply these changes
```python manage.py migrate```

When the migrations have already been created, for instance by the Django module developer, you only need to apply them : that's the case here".

**Comment by quique** [comment]
See #191

**Comment by lmsteffan** [comment]
Hadn't seen that, thank you.

**Comment by pydanny** [comment]
@lmsteffan, this is brilliantly written! Including it with minor edits!

**Comment by pydanny** [comment]
🚢 🧀
