### ISSUE TITLE
Chapter 36.2: Use of  {% endblock %}

### ISSUE THREAD

**Issue by nicomanso** [feldroy/django-crash-course#222]
##  Description 

We are using 

```
{% endblock %}
```
and

```
{% endblock <block_name> %}
```

## Possible Solutions

Use only {% endblock %} or explain "for extra readability, you can optionally give a name to your {% endblock %} tag.

**Comment by pydanny** [comment]
We'll use `{% endblock XYZ %}` consistently. Thanks for the catch!
