### ISSUE TITLE
54.4.1: Typo in explanation for "where did the view.action (...)"

### ISSUE THREAD

**Issue by mathewsmonoo** [feldroy/django-crash-course#225]
#Location within the Book

* Chapter or Appendix: 55
* Section: 4
* Subsection: 1

## Description 

> In the end of this section, there's an ordered list with an explanation for "where did the view.action (...)", but in number 2 there's a typo: "we can call at-tritibutes" . Maybe it's because of line breaking. 

## Possible Solutions

Simply correct it from 'at-tritibutes' to 'at-tributes'.

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you @mathewsmonoo for submitting it! We will be giving attribution in the next update of the book but we need a name for you. Please let us know here what name you want to be listed under.

**Comment by mathewsmonoo** [comment]
Hello!
Please, the name is Mathews Monoo Pereira De Bellis, if that's too much,
Mathews Monoo P. Bellis is fine :)
Thanks for the quick response, congratulations for the book!
