### ISSUE TITLE
5.3 Enhance explanations on the built-in server

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#226]
## Location within the Book

* Chapter or Appendix:
* Section: 5.3 Start Up Runserver
* Subsection:

## Possible Solutions

Mention that the built-in server should be used only for development, and never on anything resembling a production environment.
For production, a real web server such as Apache, Gunicorn or uWSGI should be used.

Mention that we could pass a different IP and port as arguments.

Mention that we could use a different settings file using the `--settings` option.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
