### ISSUE TITLE
27.7: Enhance explanation on database tables

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#228]
## Location within the Book

* Chapter or Appendix:
* Section: 27.7 Create and Run the Initial Cheese Migration
* Subsection:

## Possible Solutions

Mention that, by default, the name of the created table follows the pattern `<app>_<model>`, 
but that we could choose a different name using the `db_table` attribute in the `Meta` section
of the model class.

Mention that, unless otherwise indicated, Django silently adds an `id` integer field,
which is automatically incremented, to be used as primary key.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
