### ISSUE TITLE
Explain forms in Django

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#231]
## Description 

The book doesn't explain how we can create our own forms.

## Possible Solutions

Explain the use of `forms.Form` and `forms.ModelForm`.

I guess you may want to do it in a future extension.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.

**Comment by quique** [comment]
Thanks for considering my suggestion!
Hopefully it will be fulfilled in the future  :-)

**Comment by pydanny** [comment]
The 4.x edition will probably have an extra 100 pages, or we'll go for a larger PDF dimensions. 👍
