### ISSUE TITLE
56.4: Typo in 'test_cheese_update()'

### ISSUE THREAD

**Issue by fdarre** [feldroy/django-crash-course#233]
## Location within the Book

* Chapter or Appendix: 56
* Section: 4

## Description 

A comment in 'test_cheese_update()' has two hash characters instead of one.
`# # Check that the cheese has been changed`

## Possible Solutions

Remove one of the hash characters -> "# Check that the cheese has been changed"

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! We will be giving attribution in the next update of the book. 😄 
🚢 🧀
