### ISSUE TITLE
53.3.1: Typo in test_good_cheese_list_view()

### ISSUE THREAD

**Issue by fdarre** [feldroy/django-crash-course#234]
## Location within the Book

* Chapter or Appendix: 53
* Section: 3
* Subsection: 1

## Description 

There is a typo in a comment in test_good_cheese_list_view().
`#  Get the reauest`. 
' request' is written with a 'a' instead of a 'q'.

## Possible Solutions

Correct 'reauest' to 'request'.

**Comment by Scarletbegonias68** [comment]
Thank you once again for submitting an issue!
