### ISSUE TITLE
53.3.3 Cheese object creation from Cheese Factory not necessary in test_good_cheese_create_view()

### ISSUE THREAD

**Issue by fdarre** [feldroy/django-crash-course#235]
##  Location within the Book

* Chapter or Appendix: 53
* Section: 3
* Subsection: 3

## Description 

`def test_good_cheese_create_view(rf, admin_user): `
     `   # Order some cheese from the CheeseFactory `
    `    cheese = CheeseFactory()`
     `   # Make a request for our new cheese`
      `  request = rf.get(reverse("cheeses:add"))`
      `  # Add an authenticated user`
      ` request.user = admin_user` 
      ` # Use the request to get the response` 
      ` response = CheeseCreateView.as_view()(request)` 
      `  # Test that the response is valid`
      `  assert response.status_code == 200`

This test checks that the view is returning a valid 200 HTTP status code for a GET request on the "cheeses:add" url. 
A GET request on  '/cheeses/add/'  would render a blank form to let the user create a Cheese object.
For the purpose of this test, there is no need to create a cheese object from the CheeseFactory.

## Possible Solutions

Delete the following lines of 'test_good_cheese_create_view()':
 `# Order some cheese from the CheeseFactory`
  `cheese = CheeseFactory()`

The comment ` # Make a request for our new cheese` would need to be modified as well.

Suggested modification : 

`def test_good_cheese_create_view(rf, admin_user): `
   `   # Make a request to get the Add Cheese form page`
    `  request = rf.get(reverse("cheeses:add"))`
      `  # Add an authenticated user`
      ` request.user = admin_user` 
      ` # Use the request to get the response` 
      ` response = CheeseCreateView.as_view()(request)` 
      `  # Test that the response is valid`
      `  assert response.status_code == 200`

**Comment by pydanny** [comment]
Good catch!

🚢 🧀
