### ISSUE TITLE
45.5 Spell / Grammar check 

### ISSUE THREAD

**Issue by nigfinch** [feldroy/django-crash-course#237]
Hello! 

Loving the book. 

## Location within the Book

* Chapter: 45
* Section: 4

## Description 

This sentence doesn't' make sense, 

> “In future Django Crash Course extensions, we’ll go over even more testing tricks that can be used be with fakes. ”

**Comment by pydanny** [comment]
No spelling issues and the grammar is sound. Is there anything in particular that doesn't make sense?

**Comment by pydanny** [comment]
LOL, @Scarletbegonias68 just pointed out the second "be".

🚢 🧀

**Comment by nigfinch** [comment]
Oh thank god ! I thought I had lost it :)
