### ISSUE TITLE
40.2 Define a CheeseFactory

### ISSUE THREAD

**Issue by bryankimani** [feldroy/django-crash-course#238]
## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection: 40.2 Define a CheeseFactory

## Description 
The following code in that section looks like
```
from django.template.defaultfilters import slugify
import factory
import factory.fuzzy
from ..models import Cheese
class CheeseFactory(factory.django.DjangoModelFactory):
    name = factory.fuzzy.FuzzyText()
    slug = factory.LazyAttribute(lambda obj: slugify(obj.name))
    description = factory.Faker('paragraph', nb_sentences=3, variable_nb_sentences=
    firmness = factory.fuzzy.FuzzyChoice(
        [x[0] for x in Cheese.Firmness.choices]
    )
    class Meta:
     model = Cheese
```
`variable_nb_sentences=` misses a value and `factory.Faker` misses a closing `)`

## Possible Solutions
Have the description line as below:
`description = factory.Faker('paragraph', nb_sentences=3, variable_nb_sentences=True)`

**Comment by pydanny** [comment]
I think the text was cut off due to formatting. You may have an older version of the book. Can you share with me the filename of the PDF or epub file you are using?

**Comment by bryankimani** [comment]
actually, the software I was using to read the epub is the one that had issues. I was using https://www.sumatrapdfreader.org/free-pdf-reader.html. Just switched to https://calibre-ebook.com/. It is all good.
