### ISSUE TITLE
20.4.2: Backticks in commit message

### ISSUE THREAD

**Issue by pqueiroga** [feldroy/django-crash-course#239]
## Location within the book

* Chapter or Appendix: 20
* Section: 4
* Subsection: 2

## Description 

Commit the first commit with a brief, descriptive message:
```
git commit \
-m "Boilerplate files generated from the `django-crash-starter` project template.
```
Push our changes:
...

The code snippet is missing a terminating double quote, but anyways, it tries to run a bash command since it is using backticks inside double quotes. The following is my terminal output:
```
$ git commit \
> -m "Boilerplate files generated from the `django-crash-starter` project template."
bash: django-crash-starter: command not found
[master (root-commit) 8668baf] Boilerplate files generated from the  project template.
 84 files changed, 3256 insertions(+)
...
``` 
See that the commit message is missing the name of the project template.
## Possible Solutions
Using single quote is better, as it will prevent this.
```
git commit \
-m 'Boilerplate files generated from the `django-crash-starter` project template.'
```
But, if for some reasons double quotes are preferred:
```
git commit \
-m "Boilerplate files generated from the \`django-crash-starter\` project template."
```

**Comment by pydanny** [comment]
🚢 🧀 

@pqueiroga You are being added to the acknowledgements section! 😄 

Also, I was in Recife and Puerto de Galinhas in October of 2014 for Python Brasil. Such a lovely place, good food, and great people. I wish I could return. 🇧🇷
