### ISSUE TITLE
22.7: UserDetailView doesn't have comments

### ISSUE THREAD

**Issue by pqueiroga** [feldroy/django-crash-course#240]
##  Location within the Book

* Chapter or Appendix: 22
* Section: 7
* Subsection:

## Description 

Code snippet for UserDetailView has the following comments, in the book
```python3
# These Next Two Lines Tell the View to Index
#   Lookups by Username
slug_field = 'username'
```
But in the code generated by `cookiecutter`, these comments are missing. I think this might not be too relevant, but when checking the project for future reference it might be useful to have these.
## Possible Solutions
Include those comments in the code generated by `cookiecutter`.

**Comment by pydanny** [comment]
Done! See https://github.com/feldroy/django-crash-starter/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/views.py#L13-L18

**Comment by pydanny** [comment]
🚢 🧀
