### ISSUE TITLE
1.3.1: Typo

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#243]
## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection: 1.3.1 Installing VSCode on Windows

## Description 

>  Restart the Windows after the installation is finished.

## Possible Solutions

Restart Windows after the installation is finished.

**Comment by Scarletbegonias68** [comment]
Changes were made, thanks again for submitting! 😄 
🚢 🧀
