### ISSUE TITLE
1.4.1 Confusing statement

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#244]
## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection: 1.4.1 Installing Git on Windows

## Description 

> To confirm that the git was installed successfully, Open a terminal (Anaconda Prompt)
> and type `git --version` and press ENTER

## Possible Solutions

Conda has not been installed yet (it will be in next section, 1.5), so the reader won't be able to open Anaconda Prompt.

Also, the grammar of the sentence doesn't look good to me.

**Comment by luzfcb** [comment]
🚢 🧀 
@quique Thanks again.
