### ISSUE TITLE
23.2 Updating UserDetailView redundant

### ISSUE THREAD

**Issue by leonlan** [feldroy/django-crash-course#245]
## Location within the Book

* Chapter or Appendix: 23
* Section: 2
* Subsection: N/A

## Description 
After adding the bio field to the User model, the following is mentioned:
> However, the bio still isn’t on the user update form, and we have no way to edit it. That’s because we still have to update UserUpdateView and UserDetailView.

Updating UserDetailView here is redundant and might be confusing to users. It only becomes necessary in Section 23.4.

## Possible Solutions

- Remove the mention of UserDetailView here. 
- Another suggestion would be to further clarify why we need to change both views.

**Comment by pydanny** [comment]
🚢 🧀
