### ISSUE TITLE
25.2.1 Number of tests incorrect

### ISSUE THREAD

**Issue by leonlan** [feldroy/django-crash-course#246]
## Location within the Book

* Chapter or Appendix: 25
* Section: 2
* Subsection: 1

## Description 
The following explanation is given after performing the tests: 

>

> Let’s go over what happened step-by-step:
> 1. Django created a test database, so there’s no chance of it
> hurting our real data.
> 2. Django ran 8 tests in 1.94 seconds, then reported ‘OK’.
> That means all the tests pass.
> 3. Django finally destroyed the test database, making it possible
> to run the tests again with a clean slate. 
> If any of those 8 tests had failed, Django would have reported the
> failures to us via error messages. These failure messages indicate
> where the problem has occurred.

>
However, there are 9 tests as indicated in the following code block snippet:

```
Test session starts
<snip various coverage warnings>
platform: darwin, Python 3.8.1, pytest 5.3.4, pytest-sugar 0.9.2
django: settings: config.settings.test (from option)
rootdir: /Users/drg/projects/everycheese, inifile: pytest.ini
plugins: sugar-0.9.2, django-3.8.0
collecting ...
everycheese/users/tests/test_forms.py ✓ 12% █▍
everycheese/users/tests/test_models.py ✓ 25% ██▌
everycheese/users/tests/test_urls.py ✓✓✓ 62% ██████▍
everycheese/users/tests/test_views.py ✓✓✓✓ 100% ██████████
Results (1.94s):
9 passed
```

## Possible Solutions
Change 8 to 9.

**Comment by pydanny** [comment]
Thank you! 🚢 🧀
