### ISSUE TITLE
1.5.3 Installing Conda on Linux - 

### ISSUE THREAD

**Issue by Day0Dreamer** [feldroy/django-crash-course#247]
## Location within the Book

```
5. Follow the instructions on the screen. If unsure about any
setting, accept the defaults. We can change them later.
```
## Description 

By default conda doesn't init, we have to init it to be able to continue with the flow

## Possible Solutions
Change to "Type yes when asked for init"

**Comment by pydanny** [comment]
🚢 🧀 

Got a real name we can use to give you attribution in the book?
