### ISSUE TITLE
52 Missing assertion in test_models.py

### ISSUE THREAD

**Issue by leonlan** [feldroy/django-crash-course#248]
## Location within the Book

* Chapter or Appendix: 52 
* Section: N/A
* Subsection: N/A

## Description 
In Section 42.6, there are two assertions in the `test__str__()` method in `cheeses/tests/test_models.py`.

```
def test___str__():
    cheese = CheeseFactory()
    assert cheese.__str__() == "cheese.name"
    assert str(cheese) == "cheese.name"
```

In Section 52, one of the assertions has gone missing:

```
def test__str__():
    cheese = CheeseFactory()
    assert cheese.__str__() == cheese.name
```

## Possible Solutions
* Add `assert str(cheese) == "cheese.name"` to the snippet in Section 52.

**Comment by pydanny** [comment]
🚢 🧀
