### ISSUE TITLE
22.7 Capitalization Error

### ISSUE THREAD

**Issue by calebmarkovich** [feldroy/django-crash-course#249]
##  Location within the Book

* Chapter or Appendix: 22
* Section: 7
* Subsection:

## Description 

> 22.7 Introducing UserDetailview

## Possible Solutions
Correct to UserDetailView, with a capital 'V' for View.

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! We will be giving attribution in the next update of the book. 😄 
🚢 🧀
