### ISSUE TITLE
Add a keyword index at the end

### ISSUE THREAD

**Issue by guanicoe** [feldroy/django-crash-course#252]
Hi two things first: there is a typo in the default message for github "...tODOs are markers **to** to let you know we..."

Second, it would be nice to have an index with keywords at the end. Especially for printed version. 

Thanks

**Comment by pydanny** [comment]
1. Removed extra 'to'
2. We agree. The book would already have an index, but we are dealing with an off-by-2 bug in the index generation. 😒

**Comment by pydanny** [comment]
Our current R-Markdown powered build process makes this unworkable. While we can generate an index, the result is innaccurate. We might not be able to get it into the book for this edition.

**Comment by pydanny** [comment]
Hey! Unfortunately this is not a fixable problem for our current build system. Converting it to another system will take more time than what we have. For the next edition (4.x) we'll definitely include an index.
