### ISSUE TITLE
1.4.4 Configuring Git (beta 20200414)

### ISSUE THREAD

**Issue by captkidd** [feldroy/django-crash-course#255]
Currently reads:
$ git config --global user.name "Replace this by your full name"
$ git config --global user.email replace.by.your.email.@sample.com

seems awkward to me...

Suggest changing to read:
$ git config --global user.name "replace this with your full name"
$ git config --global user.email "replace this with your email address"

**Comment by pydanny** [comment]
🚢 🍨
