### ISSUE TITLE
1.6.1 Installing PostgreSQL on Windows (beta 20200414)

### ISSUE THREAD

**Issue by captkidd** [feldroy/django-crash-course#256]
This is a minor issue but recommend unchecking the Stack Builder option at the end of the install. Could be a confusing diversion for newbies.

**Comment by pydanny** [comment]
Closing this as Microsoft and EnterpriseDB are not officially supporting Windows at this time. This was causing us to spend hours and hours every week supporting Windows users, often with very different resolutions per user.

Our plan is to eventually move all Windows users to WSL2 as that stabilizes and matures in the months to come.
