### ISSUE TITLE
1.6.1 Installing PostgreSQL on Windows (beta 20200414)

### ISSUE THREAD

**Issue by captkidd** [feldroy/django-crash-course#257]
The installation process did not add postgres to my path environment variable. I had to manually add the following path: c:\Program Files\PostgreSQL\12\bin

**Comment by pydanny** [comment]
Closing this as Microsoft and EnterpriseDB are not officially supporting Windows at this time. This was causing us to spend hours and hours every week supporting Windows users, often with very different resolutions (including this one).

Our plan is to eventually move all Windows users to WSL2 as that stabilizes and matures in the months to come.
