### ISSUE TITLE
18.3 Start PostgreSQL if Needed (beta 20200414)

### ISSUE THREAD

**Issue by captkidd** [feldroy/django-crash-course#259]
This step is just a check to see that PostgreSQL is running. In my case it was, so when I entered the createdb command I got the "password:" prompt. It wasn't obvious to me whether I was supposed to enter a password and keep going or ??? 

Suggest adding a step to do a ctrl-brk  to exit the dialog if you successfully get the password prompt.

**Comment by pydanny** [comment]
Closing this as Microsoft and EnterpriseDB are not officially supporting Windows at this time. This was causing us to spend hours and hours every week supporting Windows users, often with very different resolutions per user.

Our plan is to eventually move all Windows users to WSL2 as that stabilizes and matures in the months to come.

**Comment by pydanny** [comment]
Reference showing modern There is no support for Postgres 11 and 12 on Windows 10: https://www.postgresql.org/download/windows/
