### ISSUE TITLE
18.5 How to Create It (beta 20200414)

### ISSUE THREAD

**Issue by captkidd** [feldroy/django-crash-course#260]
I struggled getting through this section. Entering the "createdb everycheese" command string resulted in prompting for a password (good) but my postgres password wouldn't work. Finally figured out the username was set to my Windows account username, not the postgres database username. Here is what ending up working for me: 

"createdb --username=postgres everycheese"

**Comment by pydanny** [comment]
Closing this as Microsoft and EnterpriseDB are not officially supporting Windows at this time. This was causing us to spend hours and hours every week supporting Windows users, often with very different resolutions per user.

Our plan is to eventually move all Windows users to WSL2 as that stabilizes and matures in the months to come.
