### ISSUE TITLE
18.7 Run the Migrations (beta 20200414)

### ISSUE THREAD

**Issue by captkidd** [feldroy/django-crash-course#261]
On my Windows platform I could not get the "python manage.py migrate" command string to run without throwing a long trace of ugly errors. This is what worked for me:

Before running migration, do this command string:

"set DATABASE_URL=postgres://postgres:yourpassword@localhost:5432/everycheese"

**Comment by pydanny** [comment]
Closing this as Microsoft and EnterpriseDB are not officially supporting Windows at this time. This was causing us to spend hours and hours every week supporting Windows users, often with very different resolutions per user.

Our plan is to eventually move all Windows users to WSL2 as that stabilizes and matures in the months to come.
