### ISSUE TITLE
Tips and Warning icons in Kindle-mobi format overwrite text, multiple icons where there should be only one

### ISSUE THREAD

**Issue by martindegroot** [feldroy/django-crash-course#263]
## Hello Daniel and Audrey,

The problem/issue I want to mention is in the Kindle/mobi edition. It concerns the places where the tips icons and warning icons are used. In the Introduction chapter, after some conventions used in this book, and at the beginning of the chapter "The Ultimate Django Setup" before section 1.1 Goal: ...

I will paste a screenshot hereafter, which will make the problem clear immediately.

![afbeelding](https://user-images.githubusercontent.com/1891155/81391259-14f68200-911d-11ea-88a9-26a24b1da2db.png)

 The second place where the same problem occurs is in the Chapter: The Ultimate Django Setup, in the first section, just before the secion 1.1 Goal: A Professional-Quality Development Environment

And a screenshot of the second place where I found this problem:

![afbeelding](https://user-images.githubusercontent.com/1891155/81391684-c85f7680-911d-11ea-9bd8-0760471632f8.png)
![afbeelding](https://user-images.githubusercontent.com/1891155/81392458-014c1b00-911f-11ea-8a88-180ae1f2a28a.png)

It is likely that all other places in the Kindle/mobi edition where these icons for tips and warnings are used will also have this problem, but I have only come to the Introduction chapter and the Ultimate Django Setup chapter so far.

Greetings, Martin de Groot

```

## Possible Solutions

**Comment by pydanny** [comment]
Resolved in the latest update by colored borders. We're fine tuning the color scheme over the next few days.

**Comment by pydanny** [comment]
🚢 🍨
