### ISSUE TITLE
25.2 "coverage run -m pytest" emits several "already-included" warnings

### ISSUE THREAD

**Issue by heitorchang** [feldroy/django-crash-course#264]
##  Location within the Book

* Chapter or Appendix: 25.2 Running Tests

## Description 

I am following the book with Windows 10. Running `coverage run -m pytest` generates several warnings that appear irrelevant to me. 

A warning looks like this:

```
Coverage.py warning: Already imported a file that will be measured: 
c:\users\neo\miniconda3\envs\everycheese\lib\site-
packages\django\templatetags\i18n.py (already-imported)
```

## Possible Solutions

Add the following line to the end of `.coveragerc` in the root directory:

`disable_warnings = already-imported`

**Comment by pydanny** [comment]
OMG that was it! I don't know why, but we've been stuck on that one for a very long time and couldn't figure it out. Thank you so much!

🚢 🧀

**Comment by heitorchang** [comment]
Learning to use conda effectively (from reading Django Crash Course) saved me from a lot of headaches, even if my project doesn't use Django so far. Thank you for writing this book!
