### ISSUE TITLE
Explain the cookiecutter option `windows [n]`

### ISSUE THREAD

**Issue by heitorchang** [feldroy/django-crash-course#265]
# Location within the Book

* Chapter or Appendix: 16.3.2 Run the cookiecutter command

## Description 

The end of the subsection reads "Let’s not worry if we don’t understand what every single value
means. We’ll learn more as we progress through this book."

However, I didn't find anything later on that explains the option `windows [n]:` that appears after `timezone [UTC]`. Does it have to do with the operating system Windows? I just accept the default `[n]`.

**Comment by pydanny** [comment]
Explained!
