### ISSUE TITLE
1.5 Tip: Duplicate 'poetry'

### ISSUE THREAD

**Issue by dfundingsland** [feldroy/django-crash-course#266]
## Chapter 1.5
In the **Tip** sub-section for environmental control tools.

## Description
poetry is mentioned twice in `More advanced readers might already be proficient with tools like virtualenv, poetry, poetry, docker`

## Additional Comments
Though not necessarily relevant to the content of your book, you may also wish to mention Pipenv, pyenv, etc.

**Comment by Scarletbegonias68** [comment]
We just corrected the extra word, thank you for submitting it! We will be giving attribution in the next update of the book. Can you provide us the name you would like used? 😄 
🚢 🧀

**Comment by dfundingsland** [comment]
You can use David Fundingsland. Thanks!
