### ISSUE TITLE
Several chapters: No code coloring or background color

### ISSUE THREAD

**Issue by Enetrati** [feldroy/django-crash-course#268]
## Description 
In the following sections code needs code coloring for readability.
12.3, 13.2 

And the following sections there is no background coloring for terminal commands or output:
16.5.1, 17.1, 24.2 

## Possible Solutions
Please add code coloring

**Comment by pydanny** [comment]
🚢 🍨

**Comment by pydanny** [comment]
What is your name so we can give you proper attribution in the book?

**Comment by Enetrati** [comment]
@pydanny Chris Dorsman    :)

**Comment by Enetrati** [comment]
Oops
