### ISSUE TITLE
23.2 Clarify instructions

### ISSUE THREAD

**Issue by Enetrati** [feldroy/django-crash-course#271]
## Location within the Book
Chapter 23.2

## Description 

> If grammar, enter problematic text here, otherwise delete this line.

Following sentences are little bit messy:

" Create and Run Migrations To do this, we can either:
• Stop runserver and use the same terminal, or 
• Open up a new commandline tab or window where we run makemigrations and migrate
Then make and apply our migrations as usual:
(picture of commands)"

## Possible Solutions
 Create and Run Migrations To do this, we can either:
• Stop runserver and use the same terminal, 
Or 
• Open up a new commandline tab or window
where we run:
(picture of commands)

**Comment by pydanny** [comment]
Thanks for the suggestion! Can you provide your full name so we can attribute you correctly within our book?

**Comment by pydanny** [comment]
🍨 🧀

**Comment by Enetrati** [comment]
@pydanny Chris Dorsman :)

**Comment by pydanny** [comment]
Adding your name! :)
