### ISSUE TITLE
Windows - PostgreSQL 18.4.1

### ISSUE THREAD

**Issue by MeloWise5** [feldroy/django-crash-course#273]
18.4.1 What to Name it?

When installing PostgreSQL, i was not allowed to save a user without a password. So the code in the book gave me an error saying i need to give a password for the user to access the database. 

This is the code in the book. 

```
DATABASE = {
"default": env.db(
             "DATABASE_URL", default="postgres:///everycheese"
   )
}
```

I had to change it to this since the user had to have a password. I did not know where to set the password to make the books code work. 

```
'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'everycheese',
        'USER': 'Nathan',
        'PASSWORD': '**********',
        'HOST': 'localhost',
        'PORT': '',
    }
```

I kept getting an error 

`django.db.utils.OperationalError: fe_sendauth: no password supplied`

Hope this helps someone or makes the book a bit more clear.

**Comment by LeonT-A** [comment]
In the cookiecutter code that got cloned, my DATABASES variable is completely different...

`DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'everycheese.db'),
    }
}`

I picked all the defaults during the cookiecutter setup, so I wasn't sure if I messed up or not. I'll just change it and hope that I'm not screwing anything up...

**Comment by pydanny** [comment]
Hey! As much as wanted to get PostgreSQL working for Windows users, it's not something we could make happen in this edition.  Should circumstances change, it is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
