### ISSUE TITLE
Windows - PostgreSQL 18.5

### ISSUE THREAD

**Issue by MeloWise5** [feldroy/django-crash-course#274]
This might not be in the scope of your book. BUT....

In 18.5 the book tells us to run this command.

`createdb everycheese`

This command can't be run until you add a environment variable to windows so you can access Postgre commands via the command line. 

I had to make the follow paths.

```
C:\Program Files\PostgreSQL\12\bin
C:\Program Files\PostgreSQL\12\lib
C:\Program Files\PostgreSQL\12\
```

I would just add a tip on that page let the user know they should have done this during PostgreSQL installation.

**Comment by LeonT-A** [comment]
Yeah, this got me for a bit, and should definitely be included in the setup.

As a user brand-new to databases, I have no clue how they work and didn't want to mess with anything I wasn't told to (Especially when it's asking me for credentials during installation... what?).

**Comment by LeonT-A** [comment]
I'd like to report a related issue:

After having to add PostgreSQL to the path, simply running
```
createdb everycheese
```

would not work. It was requesting a password and the only password up to this point (The one created during installation) was not working. Instead, I had to use...

```
createdb -U username=postgres everycheese
```

It was defaulting to using my windows username, which obviously didn't exist in the program. Using this I was able to specify the username (the default assigned during the installation) and then the password that I created for it worked.

**Comment by contadorpl** [comment]
> I'd like to report a related issue:
> 
> After having to add PostgreSQL to the path, the code provided in the book would not work...
> 
> ```
> createdb everycheese
> ```
> 
> It was requesting a password and the only password up to this point (The one created during installation) was not working. Instead, I had to use...
> 
> ```
> createdb --username=postgres everycheese
> ```
> 
> It was defaulting to using my windows username, which obviously didn't exist in the program. Using this I was able to specify the username (the default assigned during the installation) and then the password that I created during installation worked.

i have worked on it 2 days! thanks

have you had any problems when run 'python manage.py migrate' or runserver?

**Comment by pydanny** [comment]
@LeonT-A I appreciate the reporting of an issue, but next time please open a new issue and mention the possibly related issue.

This makes it much easier for us to track what needs to be done when our supporters keep issues clean. 😄

**Comment by pydanny** [comment]
Hey! As much as wanted to get PostgreSQL working for Windows users, it's not something we could make happen in this edition.  Should circumstances change, it is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
