### ISSUE TITLE
Windows - PsycoPG2 18.6 - Local Requirements

### ISSUE THREAD

**Issue by MeloWise5** [feldroy/django-crash-course#275]
PsycoPG2 was not included in the Local Requirements Dependencies download. 

You have to manually install that one.

`pip install PsycoPG2`

Not sure if i am the only one. But i tried it twice and READ all the installs to find it was missing.

**Comment by pydanny** [comment]
Hey! As much as wanted to get PostgreSQL working for Windows users, it's not something we could make happen in this edition.  Should circumstances change, it is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
