### ISSUE TITLE
Explore winget as an option for Windows users

### ISSUE THREAD

**Issue by pydanny** [feldroy/django-crash-course#279]
Winget looks awesome! Too bad it's only for Windows 10 users. 

https://docs.microsoft.com/en-us/windows/package-manager/winget/

# Plan

1. [ ] Try it out ourselves for PostgreSQL installations for Windows 10 users.
2. [ ] Invite readers on Windows 10 to try it out.
3. [ ] If it works to general satisfaction, change our instructions for Windows 10 users. For Windows 7 users, send them to a document in this repo.
4. [ ] Finally relax now that most of our Windows-using readers are in a good place.

**Comment by luzfcb** [comment]
Currently, a `winget` package for PostgreSQL has not yet been created

This repository list the available `winget` packages:
https://github.com/microsoft/winget-pkgs/tree/master/manifests

**Comment by luzfcb** [comment]
https://github.com/microsoft/winget-pkgs/pull/1728
