### ISSUE TITLE
createdb is not working

### ISSUE THREAD

**Issue by contadorpl** [feldroy/django-crash-course#281]
## Location within the Book

* Book build date (Is the date on page 1):
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 
* Section:
* Subsection: 18.5

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
when i try 'createdb' in anaconda prompt it ask me for password

## Possible Solutions

**Comment by luzfcb** [comment]
@contadorpl Two questions:
1 - can you, please add the *Book build date* on the issue description. (Is the date on page 1) 
2 - What the Operating system you using? Windows 10, Ubuntu, or Mac OSX?

**Comment by contadorpl** [comment]
> @contadorpl Two questions:
> 1 - can you, please add the _Book build date_ on the issue description. (Is the date on page 1)
> 2 - What the Operating system you using? Windows 10, Ubuntu, or Mac OSX?

for what? noboby is answering this
