### ISSUE TITLE
test_modules.py question

### ISSUE THREAD

**Issue by denikide** [feldroy/django-crash-course#283]
In test_modules.py we have following row:

`def test_user_get_absolute_url(user: User):`

And I am struggling to find more information about the "user: User" part of the code.

Is this some kind of instantianization of the User class or what is it?

**Comment by luzfcb** [comment]
@denikide 

> Is this some kind of instantianization of the User class or what is it?

Are the Python's Type Annotations/.

It is an optional syntax to indicate the expected type for a given variable, argument, or function/method return. 

Currently, the Python interpreter reference implementation (called [CPython](https://github.com/python/cpython)) does nothing with the information provided by this optional syntax, however, if you use it in your project, Pycharm IDE can read it and will help you analyze and detect errors more quickly.

https://stackoverflow.com/a/32558710

https://www.python.org/dev/peps/pep-0484/
https://www.python.org/dev/peps/pep-0526/
