### ISSUE TITLE
29.2 Create a Module for Cheese Model Tests

### ISSUE THREAD

**Issue by CoreyCCarter** [feldroy/django-crash-course#285]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Book build date (Is the date on page 1): May 30, 2020
* Book format (PDF, Epub or Mobi): Mobi
* Chapter or Appendix: 29
* Section:2
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 
I followed the instructions as presented in the text however, my tests fail. 

ImportError while importing test module '~/Documents/projects/django/everycheese/everycheese/cheeses/tests/test_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
everycheese/cheeses/tests/test_models.py:2: in <module>
    from .models import Cheese
E   ModuleNotFoundError: No module named 'everycheese.cheeses.tests.models'

========================================================== short test summary info ==========================================================
FAILED everycheese/cheeses/tests/test_models.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

## Possible Solutions
Am I missing something?

link to repo:https://github.com/CoreyCCarter/everycheese/tree/master/everycheese/cheeses/tests

**Comment by luzfcb** [comment]
@CoreyCCarter 
On your `test_models.py`, replace `from .models import Cheese` by `from ..models import Cheese` or `from everycheese.cheeses.models import Cheese` 🧀 

Interpret the dot character as a synonym for `the directory in which this file is contained`.

**Comment by CoreyCCarter** [comment]
@luzfcb My gosh! I should I have known that! I was one directory off and I knew that but didn't think to use 2 dots! Thank You so much!
