### ISSUE TITLE
how to explore django methods source code from within vscode?

### ISSUE THREAD

**Issue by IdanBanani** [feldroy/django-crash-course#288]
is it possible to inspect/see definition of specific methods/attributes of Django from vscode without googling while using conda/virtual environments and without debugging

what about Pycharm?

**Comment by KKP4** [comment]
Right-click on the method - Go to definition or press F12

**Comment by IdanBanani** [comment]
I asked because this had no effect. Maybe I did something wrong?

**Comment by pydanny** [comment]
You need to set VS code to point at the right python interpreter. We'll add that to the book if it's not there yet.

**Comment by pydanny** [comment]
:ship: 🧀
