### ISSUE TITLE
Suggestion about promoting open source over commercial solutions

### ISSUE THREAD

**Issue by rsommerard** [feldroy/django-crash-course#290]
## Location within the Book
Chapter 6: Create a Django-Superuser and every other chapter which provide this tips
Section 2: Run createsuperuser
Subsection: Copy this password into a password manager!

## Description

    Instead, lean on secure pass-word managers like 1Password or open source options.

It could be nice to promote open source and free solution like `Bitwarden` or `KeePass` over commercial one :)

## Full text:

It’s bad practice to use simplistic passwords, even for local development. We want to promote strong security habits and this is one of them. Also, don’t stick passwords into plaintext or spreadsheet files. Instead, lean on secure pass-word managers like Bitwarden or Keepass or commercial options.

**Comment by pydanny** [comment]
We'll include those open source options. However, we are hesitant to recommend anything that we are unfamiliar with using. For the time being we'll recommend 1Password first, and list `Bitwarden` and `KeePass` as open source options.

**Comment by pydanny** [comment]
🚢 🧀
