### ISSUE TITLE
Section 24.2: the magical linebreaksbr

### ISSUE THREAD

**Issue by rsommerard** [feldroy/django-crash-course#291]
## Location within the Book

* Chapter 24: Adding Bio to User Detail Template
* Section 24.2: Add Line Breaks

## Description 

To render the line break on the web page you use the `linebreaksbr` helper but this one comes out of nowhere.

```
<p>{{ object.bio|linebreaksbr }}</p>
```

## Possible Solutions

It could be useful to explain the concept or if it is explain in the next chapters, to indicate it.

**Comment by pydanny** [comment]
🚢 🧀
