### ISSUE TITLE
23.2.1 Unintelligible sentence

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#293]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Book build date (Is the date on page 1): 20200623
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 23
* Section: 2
* Subsection: 1

## Description 

> we need to apply these changes that’s called a migration.

## Possible Solutions

we need to apply these changes. That is called a migration.

**Comment by pydanny** [comment]
🚢 🧀
