### ISSUE TITLE
Set up User to use it with others tests instead of using admin_user for authenticate views

### ISSUE THREAD

**Issue by kamranhossain** [feldroy/django-crash-course#294]
I think it will be better if we can set up users to use it with other tests instead of using admin_user for authenticate_views. Personally, I don't think that everyone will like to use admin_user for their test. So I make this suggestion. I hope it will be helpful for devs. 
Thanks.

**Comment by pydanny** [comment]
Great idea! I think we can use this code:

``` python

**Comment by pydanny** [comment]
🚢 🍨
