### ISSUE TITLE
20.4.2: potential for trouble if Git not already configured

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#296]
## Location within the Book

* Book build date (Is the date on page 1): 6/23
* Book format (PDF, Epub or Mobi): 
* Chapter or Appendix: 20
* Section: 4
* Subsection: 2

## Description 

Maybe the boxed "Before the next step" would benefit from another sentence saying where you should be (folder and environment) when you're finished configuring Git.

I put off configuring Git when I went through the initial instructions/hellodjango project. Those instructions have you get to the "Anaconda prompt" (which puts you in the base environment). Could trip someone up when they return to 20.4.2 and try to commit or when in 20.5 you direct them to "go back to our terminal" to check the log. 

Also in 20.5, I was a little confused by "in our browser, refresh our project page." I thought you meant the browser pointed at the local everycheese project home page, but you had said to stop the runserver back in 20.4.1. You mean in 20.5, I think, the browser as pointed at the project page *on GitHub.* Right?

> If grammar, enter problematic text here, otherwise delete this line.

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

**Comment by pydanny** [comment]
🚢 🧀
