### ISSUE TITLE
18.6 — missing reminder?

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#297]
## Location within the Book

* Book build date (Is the date on page 1): 6/23/20
* Book format (PDF, Epub or Mobi): 
* Chapter or Appendix: 18
* Section: 6
* OS: Windows 10

## Description 

The text of this 18.6 reminds you to activate the everycheese environment before installing the dependencies, but it omits a reminder that you should be in the everycheese project folder. 18.2 of course tells you to go there, but then comes a bunch of stuff about Postgres that is irrelevant to Windows users. If the user is interrupted before they change to the project folder, or if they fiddle around while skimming the stuff on Postgres, they might not (still) be in the project folder when they get to 18.6. Anyway, I managed to attempt the install from the wrong folder and suffered a confusing failure at that point.

**Comment by pydanny** [comment]
🚢 🧀
