### ISSUE TITLE
23.2 — minor clarification

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#298]
* Book build date (Is the date on page 1): 6/23

You say "apply our migrations as usual" but you've never before mentioned a migrate command with an appended specifier (here, "users") and you've previously had us doing "...migrate" but not "...makemigrations" -- so it's the "as usual" that threw me, thought I had missed something. 

Must 'migrate' always precede 'makemigrations'?

**Comment by pydanny** [comment]
🚢 🧀
