### ISSUE TITLE
23.1 — instruction to save the file

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#299]
6/23 build

23.1 says to add the field to the model but perhaps given the bonehead I seem to be, might also remind me to save users.py before proceeding to 23.2. Again, this omission(?) is mainly noticeable because the instructions are in general so step-by-step specific—since you're telling me to do every last little thing, when you don't tell me to do something, my temptation is to think I don't need to do it. 

There is a general instruction in the intro as to the necessity of saving files: "As always, let's not forget to save our work!" (9.2). But "as always" isn't perhaps clear enough: saving to protect us from lost work is what it implies, especially when you use "save" to refer to git steps as well as the saving of individual files. Whereas, the issue I had with 23.1 is that saving is necessary before website can reflect the changes to models.py.

You _do_  give an explicit save instruction for changes to admin.py in later sections, eg 31.4.

**Comment by pydanny** [comment]
Thank you so much for mentioning this, it is an awesome issue. In fact, we are adding the following to the book based on this issue:

> **Save your files constantly!**

> Anytime you leave a code file to visit another file or run something on the command, save your file.  In fact, with VS Code, we recommend going to the file menu at the top of the screen and choosing "Auto Save". This will autosave files within VS Code any time you leave them.
