### ISSUE TITLE
23.2.1 — language detail

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#300]
6/23

You say, "When the migrations have already been created, for instance by the Django module developer, we only need to apply them: _that’s the case here._" But that's not the case here, we've just been asked to run migrations created by us, not the Django developers.

**Comment by pydanny** [comment]
:ship: :cheese:

How about this?

> When migrations have already been created, for example by third-party libraries, we only need to apply them. That's not the case here, we are making our own (`makemigrations`) and running them (`migrate`).
