### ISSUE TITLE
23.3 and 24.1 — hunh, no migration needed?

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#301]
For the beginner, it's confusing that just after you've stressed the need to run migrations after changing something (23.2.1) you then have us change things (23.3, 24.1) without a need to run migrations. Everything worked, but I hesitated to proceed without first running the migrations given the clear statement they are needed. Must be that whether you need to migrate depends on the the type of change. A few words on this perhaps at the end of 23.2.1, as in, "But you don't always need to migrate. Some changes ..."

**Comment by pydanny** [comment]
🚢 🧀
