### ISSUE TITLE
1.5.4 Missing word

### ISSUE THREAD

**Issue by acousticat** [feldroy/django-crash-course#303]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Book build date (Is the date on page 1):beta-20200623
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 1
* Section: 5
* Subsection: 4  Why We Install Python 3.7 Downloads for Conda

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> but in later chapters we’ll how we can easily create Python 3.8 environments.

## Possible Solutions
   -- we'll _show_ how

## Your full name so we can provide accurate credit within the book
Tim Wilson

**Comment by pydanny** [comment]
🚢 🧀
