### ISSUE TITLE
Context for Code insertion - get_context_data (Beginners)

### ISSUE THREAD

**Issue by kmurray24** [feldroy/django-crash-course#304]
I ran across section 12.3 where you add the following:
```
def get_context_data(self, **kwargs):
context = super().get_context_data(**kwargs)
context['my_statement'] = 'Nice to see you!'
return context
```
I am fairly new to Django and find that when you run into a problem is can stop you dead in your tracks and you cannot move forward.  Very frustrating for someone new to the game and something this books goal intends to help avoid. 

I entered this as instructed by the book, but the code did not get executed.  I must have spent more than an hour trying to figure out why.  The server starts up fine and the page executes fine, just the "Nice to see you!" does not appear.  Also, I noticed that VS Code shows an error for the super() reference. 

**This was until I realized that the method needs to be indented to work properly.**
Always adding **context** whether by example, use case, or verbiage to any documentation is soooo helpful.  
When you say to do something always add **context** in some manner.  It's all about the **context** when new to something. This builds the foundation for someone.

I'm not asking you to really mention any additional verbiage, but If you could just add **context** to any surrounding code with other code I think this would have eliminated my frustration and I'm sure lots of others along the way.  It definitely would have shown me that the method should have been indented and I could have progressed along in your excellent book.

Thanks for listening to someone following along in your book.   Hope this helps the cause for other new people as well!
This is the best book so far I have come across.  Keep up the good work.  
Thanks,
Ken Murray

* Book build date (Is the date on page 1):  6/23
* Book format (PDF, Epub or Mobi):   PDF
* Chapter or Appendix: 
* Section: 12.3
* Subsection:

## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Book build date (Is the date on page 1):
* Book format (PDF, Epub or Mobi): 
* Chapter or Appendix: 
* Section: 12.3
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> If grammar, enter problematic text here, otherwise delete this line.

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

**Comment by pydanny** [comment]
🚢 🧀 

Great point! Here's what we added

> **Indent Code Per the Examples!**

> With Python, indentation is of absolute importance. It is how code blocks are defined. In this case, make certain that  `get_context_data()` is indented from the class. Also, the last three lines of the `get_context_data()` method are indented.

> This isn't just a code clarity issue in Python, if it is not done then Python will throw errors.

**Comment by kmurray24** [comment]
Great!
