### ISSUE TITLE
Context for executing commands (everycheese)

### ISSUE THREAD

**Issue by kmurray24** [feldroy/django-crash-course#305]
It is not clear if I should be in the (everycheese) Venv when executing commands.
16.1 conda install -c conda-forge cookiecutter  (should I have my venv active)?  How do I know this?
16.3.2 cookiecutter gh:feldroy/django-crash-starter

Knowing if I should be in (everycheese) venv would greatly add context and I'm sure help out new developers.  Hope that helps

**Comment by pydanny** [comment]
🚢 🧀
