### ISSUE TITLE
41.3 through 42.2 — 'missing' CheeseFactory import in shell_plus

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#306]
(v 6/23)
Chapters 41 and 42 omit the instruction to import CheeseFactory ('from everycheese.cheeses.tests.factories import CheeseFactory'), evidently assuming we have left the shell_plus motor running after finishing Chapter 40. But you have us leaving shell_plus at least mentally at the end of 40, deleting the bogus cheese via the admin panel and running git commands (which require exit from shell_plus unless one opens another terminal). If the reader happens to take a break of any length between 40 and 41 trouble is especially likely.

**Comment by pydanny** [comment]
🚢 🧀
