### ISSUE TITLE
Import error for 'assertContains'

### ISSUE THREAD

**Issue by goutomroy** [feldroy/django-crash-course#307]
I am getting import error `Cannot find reference 'assertContains' in 'asserts.py' ` for importing
`from pytest_django.asserts import assertContains`  in `chapter 52.3` of book version `beta-20200713`. What can be the problem?

Thanks in advance.

**Comment by pydanny** [comment]
I can't reproduce this error. Do you have your environment active with all your requirements installed?

**Comment by goutomroy** [comment]
Yes, mu environment is acive and I get no other import error except this one and I did **pip install -r requirements/local.txt** correctly.

**Comment by pydanny** [comment]
No one else is reporting this error. Closing this for now, we'll reopen if someone else can duplicate your error.
