### ISSUE TITLE
Templates location

### ISSUE THREAD

**Issue by onismo** [feldroy/django-crash-course#308]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-11
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 9
* Section: 9.1
* Subsection:

## Description 

> "Notice how DIRS is an empty list. As of now, Django doesn’t know where to look for templates. We’ll change that."

## Possible Solutions

Django knows where to find templates since 'APP_DIRS': True.

https://docs.djangoproject.com/en/3.0/topics/templates/#configuration

https://docs.djangoproject.com/en/3.0/intro/tutorial03/#write-views-that-actually-do-something

**Comment by pydanny** [comment]
We're putting our templates into a dedicated directory which won't work the way you are specifying.

**Comment by onismo** [comment]
Perhaps we can say instead, "Notice how DIRS is an empty list. We can change that to specify where we want Django to look for templates."

**Comment by pydanny** [comment]
🚢 🧀
