### ISSUE TITLE
venv activated, grammar

### ISSUE THREAD

**Issue by onismo** [feldroy/django-crash-course#309]
* Book build date (Is the date on page 1): 2020-07-11

* Section: 16.1
## Description 
> Make Certain the (everycheese) venv is activate

## Possible Solutions
Make Certain the (everycheese) virtual environment is activated

* Section: 18.4
## Description 
> This are the defaults, which is used by local.py for local development.

## Possible Solutions
These are the defaults, which are ...

**Comment by Scarletbegonias68** [comment]
Hello @onismo! We just corrected both of these, thank you for submitting it! We will be giving attribution in the next update of the book. What name would you like to be listed under?
🚢 🧀

**Comment by onismo** [comment]
Thank you,
Adonis Geronimo
