### ISSUE TITLE
Section 18.5 Troubleshooting for createdb everycheese

### ISSUE THREAD

**Issue by DROMZEE** [feldroy/django-crash-course#31]
### Location within the Book

* book version : alpha-20200204.pdf
* Part II EveryCheese
* Section: 17.5 How to Create It
* page 86

### apologies

Hello, 
I am french = my apologies for my english

### Description

The command line `createdb everycheese` return
> createdb: error: could not connect to database template1: FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Cédric »

the psql command `\du` return the username `CÚdric` and not 'Cédric'
with pgAdmin 4 I created the new user `cheese` and his password

is it possible to force a username when i place the command `createdb everycheese` ?

Many thank you for your work !

* W10 pro
* postgres (PostgreSQL) 12.1

**Comment by pydanny** [comment]
It might be, but I'm not at a computer until Monday to check. What I suggest you do until then is recreate your project again, this using SQLite3 instead of postgres. That way you can proceed in the book further until I can help debug the problem. 🙂

**Comment by DROMZEE** [comment]
The issue may be temporarily circumvented using the development environment on Ubuntu (WSL)

[Notebook with commands for migrate the project to WSL](https://github.com/DROMZEE/everycheese/blob/master/everycheese.ipynb)
(work in progress )

**Comment by DROMZEE** [comment]
I tested several configuration without success : 
* with PosgreSQL on Ubuntu (WSL)
* with PostgreSQL and a new user account on W10
* with SQLite on W10
* with SQLite on Ubuntu (WSL)
Apparently the SQLite parameter is not taken into account ![with SQLite on Ubuntu (WSL)](https://user-images.githubusercontent.com/12269933/74377806-f5cdaa00-4de4-11ea-9abb-330d377527df.png)

**Comment by diek** [comment]
![Screen Shot 2020-02-13 at 17 43 42](https://user-images.githubusercontent.com/1261158/74476659-9032f980-4e88-11ea-913a-b8ebfd6cb4f2.png)

**Comment by diek** [comment]
The above is Ubuntu 18, on Mac postgres.app does all this for you, creates the role of the user installing the app, and it also creates a db with the same name.
<img width="599" alt="Screen Shot 2020-02-13 at 17 49 39" src="https://user-images.githubusercontent.com/1261158/74477040-4991cf00-4e89-11ea-8955-ffe25f55334b.png">

**Comment by diek** [comment]
I do not have a PC, so I am not sure, I image it is similar to Ubuntu in concept.

**Comment by DROMZEE** [comment]
@diek  Thank you very much for your help

On the environment :
* Ubuntu 18.04.4 (WSL 2)
* PostGreSQL 12.2
* Python 3.8.1
I still have error messages for the command
`python manage.py migrate`

![Annotation 2020-02-14 2352562](https://user-images.githubusercontent.com/12269933/74574890-60b5e700-4f85-11ea-90d2-be53c9ee30a4.png)
![Annotation 2020-02-14 235256](https://user-images.githubusercontent.com/12269933/74574902-68758b80-4f85-11ea-80c7-0bf83877052f.png)

**Comment by diek** [comment]
@DROMZEE I will do a run on my linux(ubuntu) box

**Comment by diek** [comment]
I think you may need to update the connection string used by DATABASE_URL, and explicitly include all the data including the password: 
`postgres://USER:PASSWORD@HOST:PORT/DATABASE_NAME`
e.g.
`DATABASE_URL=postgres:/cedric:your_password@localhost:5432/everycheese`

**Comment by DROMZEE** [comment]
@diek Thank you very much for your help.
it worked by replacing
`"default": env.db("DATABASE_URL", default="postgres:///everycheese")`
by
`"default": env.db("DATABASE_URL", default="postgresql://test:1234@localhost:5432/everycheese")`

the documentation for version 12 of PostgreSQL specifies that it is necessary to use 

> postgresql://

* source : https://www.postgresql.org/docs/12/libpq-connect.html
