### ISSUE TITLE
1.6.1 — request for review of wording re Windows and databases

### ISSUE THREAD

**Issue by JoanEliot** [feldroy/django-crash-course#311]
* Book build date: 2020-07-13
1.6.1
Windows 10

Although I wish you'd been able to support PostgreSQL in the Crash Course, it's fine that you don't. But having now moved on to 2 Scoops I was unprepared for how negatively you view Sqlite. Please let even your alpha/beta readers of Crash Course know that you strongly recommend Postgres for serious work, that they will need to change over once you're able to supply those instruction, and that making the switch will take some work but won't be all that bad. Well, if nothing else, it might help to substitute some other word for "Fortunately" (even though Sqlite's inclusion with Python is indeed fortunate). The word's sunny implication is perhaps problematic, in the absence of offsetting advisories.

[A from-the-field report: It took me about 3 hours today to go from installing Postgres 12.3 to getting the cheese whizzer working again. Very pleased that it came together fairly quickly and without major trauma, but there were many trials and many errors along the way, and I'm very much looking forward to step-wise instructions for reference.]

**Comment by pydanny** [comment]
Thank you so much for our input. We really like SQLite, but we will temper our criticisms of it. The reason why we include those criticisms is so that SQlite is not used in production.

🚢 🧀

**Comment by pydanny** [comment]
Okay, I see now you were talking about how we refer to it in Two Scoops of Django, not in Django Crash Course.

Our opinion of Sqlite in a real production environment is based on years of experience. SQlite for development is the option we can use right now, it's not ideal, but it is what we have to work with. Part of being a professional software developer is that sometimes your development environment simply will not match production. Case in point, developing on Windows or Mac, then deploying to pretty anywhere.
