### ISSUE TITLE
Wrong directory

### ISSUE THREAD

**Issue by ksemilla** [feldroy/django-crash-course#312]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-11
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 52 Update the Cheese Model Tests
* Section: 52.1 Test Get_absolute_url()
* Subsection:

## Description 

"cheeses/test_models" : no existing directory

## Possible Solutions

Change to "cheeses/tests/test_models"

## Your full name so we can provide accurate credit within the book

Kevin Semilla

**Comment by pydanny** [comment]
🧀 🚢
