### ISSUE TITLE
The Django VSCode Extension

### ISSUE THREAD

**Issue by ahuimanu** [feldroy/django-crash-course#313]
The Django VS Code extension can be useful.  It will allow for integration with Emmet.

[https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django](url)

Caveat: you need to make some small modifications so that Emmet will work with HTML and Django Templates.  Modifications are explained in the link.

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
