### ISSUE TITLE
Git-bash default terminal for Windows users

### ISSUE THREAD

**Issue by ahuimanu** [feldroy/django-crash-course#314]
The Git-bash shell might be a better fit for Windows users as it allows most (but not all) *nix commands in the shell:

Prerequisite:
Git for Windows must be installed

Steps:

1. Open Command Pallete (CTRL + SHIFT + P)
2. Type: "Terminal: Select Default Shell"
3. Arrow down or select "Git Bash"

Usage:
Use in VS Code's terminal: (CTRL + `) backtick

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
