### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by polkapolka** [feldroy/django-crash-course#315]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Book build date (Is the date on page 1):
beta-20200713.pdf
* Book format (PDF, Epub or Mobi): 
pdf
* Chapter or Appendix:
53
* Section:
3
* Subsection:
3
Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 
On Page 270, why do you directly import instead of importing from the local file

```
from everycheese.users.tests.factories import UserFactory
```
vs
```
from .factories import CheeseFactory, UserFactory
```

## Possible Solutions

NA

## Your full name so we can provide accurate credit within the book
Phebe Polk

**Comment by pydanny** [comment]
🚢 🧀
