### ISSUE TITLE
Wording: 55.4.1 Using View Properties In Templates

### ISSUE THREAD

**Issue by mark-sevelj** [feldroy/django-crash-course#316]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Book build date: 
    2020-07-11  beta-20200713.pdf
* Book format:
    PDF
* Chapter or Appendix:
    55
* Section: 
    4 
* Subsection:
    1 Using View Properties In Templates

## Description 

This makes the form confusing because adding cheese isn’t the same as updating cheese. 
Let’s fix it by replace the current code in {% block content %} with the following more flexible approach:

## Possible Solutions
Let’s fix it by replacing the current code in {% block content %} with the following more flexible approach:

## Your full name so we can provide accurate credit within the book
Mark Sevelj

**Comment by pydanny** [comment]
🚢 🧀
