### ISSUE TITLE
Wording: 55.5 Link to the Update Form

### ISSUE THREAD

**Issue by mark-sevelj** [feldroy/django-crash-course#317]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Book build date (Is the date on page 1):
    2020-07-11 beta-20200713.pdf
* Book format (PDF, Epub or Mobi): 
    PDF
* Chapter or Appendix:
    55
* Section:
    5 Link to the Update Form
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

#### Paragraph Wording
Open templates/cheeses/cheese_detail.html in your text editor.
Right below the page ***title***, add a button link to the cheese
detail form:

#### A possible gotcha
For someone new  to add the button under 
```{% block title %}Cheeses: {{ cheese.name }}{% endblock title %}```
because as you look down the page **title** appears in the ```{% block title %}```

#### cheese_detail.html first lines of code
```
{% extends "base.html" %}

{% block title %}Cheeses: {{ cheese.name }}{% endblock title %}

{% block content %}
    <h2>{{ cheese.name }}</h2>
```
## Possible Solutions
Open templates/cheeses/cheese_detail.html in your text editor.
Add a button link inside ```{% block title %}```  below the ```<h2>``` tags.

## Your full name so we can provide accurate credit within the book
Mark Sevelj

**Comment by pydanny** [comment]
Button links won't work in `{% block title %}`. Do you mean in {% block content %} the <h2> tag?

**Comment by mark-sevelj** [comment]
Duoh. Yes that is what I meant thank you.

**Comment by pydanny** [comment]
🚢 🧀
