### ISSUE TITLE
20.2 We'll Use GitHub; What are the readers supposed to do?

### ISSUE THREAD

**Issue by chitown88** [feldroy/django-crash-course#318]
Bullet point 2 states "Add an SSH key to our GitHub profile, so that we can
push code changes to our repo." 

But I have no idea how to do that. I went to the link in the footnote, but don't know where to go from there. What are the readers supposed to do here?

**Comment by grondman** [comment]
Perhaps GitHub’s own docs are helpful here:

https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by pydanny** [comment]
The link to use, which we now mention in the book, is https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Thank you for your submission! :-)

🚢 🧀
