### ISSUE TITLE
Unnecessary footnotes for URL's

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#319]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-11
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 5
* Section: 5.4, page 57

## Description
The running text will mention some address (e.g. 127.0.0.1:8000) in the running text, for which a clickable-link is put into a footnote. This feels like double information, i.e. unnecessary footnoes.

It happens in several locations (5.4, p57; 7.4, p61; 11.4, p77; 11.6, p78; 12.4, p82; 13.3, p85; 18.8, p108; 35.3, p184 from what I found now). 

It's probably some artifact of links needing names and a location, where the name would appear in the running text and the actual address in the footnote, but it looks a bit weird if name and location are pretty much the same thing.

## Possible Solutions
Since you already have clickable links in the running text anyway, I suggest to get rid of these footnotes that don't actually add any information.

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by pydanny** [comment]
🚢 🧀
