### ISSUE TITLE
Chapter 18 tries to use Django before having it installed

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#321]
##  Location within the Book

* Book build date (Is the date on page 1): 2020-07-11
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 18
* Section: 5

## Description 
The book orders the user to call `python manage.py sqlcreate | psql`, but at this point in the book a new conda environment was created which does not have django installed in it yet.

## Possible Solutions
The fact that Django should be installed in every new conda environment is of course obvious, but perhaps it should be mentioned explicitly by either making a note in Chapter 15 where this particular new environment is set up or some general note at the beginning of the book.

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by luzfcb** [comment]
Issue related to https://github.com/feldroy/django-crash-course/issues/320#issuecomment-665086071

**Comment by pydanny** [comment]
🚢 🧀
