### ISSUE TITLE
Instructions to verify first commit to GitHub point to localhost

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#322]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-28
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 20
* Section: 5

## Description 
Text says:
> In our browser, refresh the page at http://127.0.0.1:8000. Click
on Files in the right sidebar and make sure that all our files are
there.

1. Refreshing the page we're running locally in Django obviously shows no difference with the situation _before_ committing.
2. I don't see a "Files" option in GitHub's right sidebar?

## Possible Solutions
1. I guess the reader should be refreshing the GitHub page here to see if the code was correctly _pushed_ to GitHub. Perhaps then the section should be re-titled "Verify That the Files Got _Pushed_", as correctly _committing_ will still not show anything on GitHub.
2. Not sure where the "Files"/"right sidebar" is referring to? I don't see it on GitHub:
<img width="1191" alt="Screenshot 2020-07-29 at 12 19 31" src="https://user-images.githubusercontent.com/48948330/88788631-e1fce100-d195-11ea-8bfd-0e04d1b76306.png">

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by pydanny** [comment]
Great input! Thank you!

🧀 🚢
