### ISSUE TITLE
Better explanation on grids in 44.3

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#323]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 44
* Section: 3

## Description 
Text in 44.3 says:
> The top thing that compes up is a _grid_.

In my case the top result is the _django-countries_ package. Perhaps the section could provide some more information on why we want to go for the grid result anyway and what a grid actually means on the Django Packages website?

## Possible Solutions
Simplest is to leave out "top" and explain why we want to see the grid result instead of the top result package?

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by pydanny** [comment]
🚢 🧀
