### ISSUE TITLE
How to exit shell_plus should be mentioned earlier in the book

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#325]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 51
* Section: 6

## Description 
Text mentions
> Exit the shell with Ctrl+D.

for the very first time even though `shell_plus` was used several times before in the book. When using `shell_plus` for the first time in the book (which in fact was my first time ever using `shell_plus`), it simply stated "Exit `shell_plus` again, and I simply guessed it was probably `exit` or `exit()` (which also work and don't ask "Are you sure?").

## Possible Solutions
Mention the way to exit `shell_plus` when it's first used in the book (and perhaps swap Ctrl+D for exit?)

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by pydanny** [comment]
🚢 🧀
