### ISSUE TITLE
Obsolete imports in test_views.py

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#326]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 53
* Section: 2

## Description 
Text says to add the following imports, but they're never used anywhere in the book:
```
from django.contrib.sessions.middleware import SessionMiddleware
from django.test import RequestFactory
from everycheese.users.models import User
```
It also asks the reader to import `CheeseCreateView` and later on in the book (56.3) to import `CheeseUpdateView`, but these are also not used in the tests that are written as we're directly using `client.get()`.

## Possible Solutions
Remove the imports

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by pydanny** [comment]
🚢 🧀
