### ISSUE TITLE
Result of client.post() assigned to response, but unnused

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#327]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 53
* Section: 8

## Description 
In `test_cheese_create_form_valid()`, the line
```
response = client.post(url, form_data)
```
produces an unused variable `response`. The same happens later on in 56.4 where `test_cheese_update()` is written. It's not a huge problem of course.

## Possible Solutions
Don't assign the result, or perhaps make use of the `response` variable to assert for a redirection status code?
```
assert response.status_code == 302
```

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by pydanny** [comment]
🚢 🧀
