### ISSUE TITLE
Double entries in section on beta readers

### ISSUE THREAD

**Issue by grondman** [feldroy/django-crash-course#328]
# Thanks!
I've finished the book and it was definitely helpful! This is my last reported issue, I think :)

## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 59
* Section: 2

## Description 
Some authors are mentioned twice, e.g. Mark Sevelj.
## Possible Solutions
Check for uniqueness of names.

## Your full name so we can provide accurate credit within the book
Ivo Grondman

**Comment by pydanny** [comment]
🚢 🧀
