### ISSUE TITLE
code block in PDF doesn't match current practice in section 18.4

### ISSUE THREAD

**Issue by mathemaat** [feldroy/django-crash-course#336]
## Location within the Book

* Book build date: 2020-07-29
* Book format: PDF
* Section: 18.4
* Operating system: Linux (Manjaro)

## Description 

The code block that is generated for me looks a bit different from the PDF:

```
DATABASES = {
    # Raises ImproperlyConfigured Exception
    # if DATABASE_URL Not in os.environ and
    # the "default" argument is not defined.
    # The DATABASE_URL environment variables
    # expect a value in the following format:
    # DATABASE_URL=postgres://user:password@hostname_or_ip:port/database_name
    "default": env.db(
        "DATABASE_URL", default="postgres:///everycheese"
    )
}
```

The PDF shows fewer commented lines and a more sophisticated `DATABASE_URL`, namely `default="postgres://user:passwd@localhost:5432/everycheese"`

It seems this code block has been updated in the crash starter on June 2: https://github.com/feldroy/django-crash-starter/commit/810e68cd231015159580b23edcfc701e7a148217#diff-617bba77520b582b8083406fae35d163

## Possible Solutions

Update the code block in the PDF accordingly

## Your full name so we can provide accurate credit within the book

Marc Schwartz

**Comment by pydanny** [comment]
🚢 🧀
