### ISSUE TITLE
Grammar Correction in Product Description

### ISSUE THREAD

**Issue by memarino92** [feldroy/django-crash-course#341]
## Location within the Book

In the FAQ section on the product description page, specifically the second bullet point in the CBVs or FBVs section

## Description

> The canonical example _if_ Django REST Framework

## Possible Solution
Should read
> The canonical example _is_ Django REST Framework

## Your full name so we can provide accurate credit within the book
Michael E. Marino

**Comment by pydanny** [comment]
🚢 🧀
