### ISSUE TITLE
22.4 - Misplaced Figure in "Explore the User Profile"

### ISSUE THREAD

**Issue by thorrak** [feldroy/django-crash-course#342]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 22.4
* Section: What We Get From The Users App
* Subsection: Explore the User Profile
* What operating system are you using: N/A

## Description 

Section 22.4 currently ends with the line

> It looks like this:

... but the figure (Figure 16) actually appears under section 22.5. A screenshot of what I mean from the PDF is below:

<img width="510" alt="Screen Shot 2020-08-15 at 7 48 26 PM" src="https://user-images.githubusercontent.com/2457900/90323557-d0a32b00-df30-11ea-8f2a-b18a0c894966.png">

## Possible Solutions

Move the figure to the right place in the book (assuming this isn't just a rendering issue)

## Your full name so we can provide accurate credit within the book
John Beeler

**Comment by pydanny** [comment]
🚢 :cheese
