### ISSUE TITLE
18.3 Install the Dependencies: Repeated environment info

### ISSUE THREAD

**Issue by mark-sevelj** [feldroy/django-crash-course#343]
## Location within the Book
* Book build date (Is the date on page 1):
2020-07-29
* Book format (PDF, Epub or Mobi): 
PDF
* Chapter or Appendix:
18
* Section:
3 Install the Dependencies
* Subsection:
* What operating system are you using:
  - [ X ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [ ] Linux (Other)
  - [ ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 
Repeated information to ensure environment is activated before installing requirements:-

![image](https://user-images.githubusercontent.com/31756570/90331428-c3487800-dfe6-11ea-88b0-d7a06d8c7020.png)

> If grammar, enter problematic text here, otherwise delete this line.

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

## Possible Solutions

![image](https://user-images.githubusercontent.com/31756570/90331720-4ff43580-dfe9-11ea-9ec2-7d4d9f2b0d63.png)

## Your full name so we can provide accurate credit within the book
Mark Sevelj

**Comment by pydanny** [comment]
🚢 🧀
