### ISSUE TITLE
Chapter II, 46.2 - urlpatterns tuple and list

### ISSUE THREAD

**Issue by bummmer** [feldroy/django-crash-course#344]
## Location within the Book

* Book build date (Is the date on page 1):2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: II
* Section: 46
* Subsection: 2
* What operating system are you using:
  - [X] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [ ] Linux (Other)
  - [ ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 
In the 2nd example, when changing the order of the url patterns, urlpatterns is a tuple where it was a list in previous examples.

```
urlpatterns = (
    path(
        route='',
        view=views.CheeseListView.as_view(),
        name='list'
    ),
    path(
        route='add/',
        view=views.CheeseCreateView.as_view(),
        name='add'
        ),
    path(
        route='<slug:slug>/',
        view=views.CheeseDetailView.as_view(),
        name='detail'
        ),
)
```

## Possible Solutions
Should be a list?

```
urlpatterns = [
    path(
        route='',
        view=views.CheeseListView.as_view(),
        name='list'
    ),
    path(
        route='add/',
        view=views.CheeseCreateView.as_view(),
        name='add'
        ),
    path(
        route='<slug:slug>/',
        view=views.CheeseDetailView.as_view(),
        name='detail'
        ),
]
```

## Your full name so we can provide accurate credit within the book
Jeff Robinson

**Comment by pydanny** [comment]
🚢 🧀
