### ISSUE TITLE
how to configure VSCode with Django?

### ISSUE THREAD

**Issue by mathemaat** [feldroy/django-crash-course#345]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format: PDF
* Section: 1.3
* What operating system are you using: Linux (Manjaro)

## Description 

The manual suggests using VSCode as the main editor. Unfortunately, my experience with VSCode is not nearly as smooth as the one I had with the trial version of the professional edition of PyCharm (which supports Django). I did install the most popular Django plugin. On top of that, I'd like to use PyLinting with PEP8 notifications enabled.

P.S. I did some online research myself, but I haven't been able to find a comprehensive (and up-to-date) list of all the plugins and settings I have to go through.

## Possible Solutions

Add a chapter (possibly in the Appendix) either to the Django crash course or to Two Scoops Django 3.X on how to configure VSCode to work properly with Django.

## Your full name

Marc Schwartz

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
