### ISSUE TITLE
Model Fields not using explicit declaration for arguments 

### ISSUE THREAD

**Issue by Delvio** [feldroy/django-crash-course#346]
## Location within the Book

* Book build date (Is the date on page 1):2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 2
* Section: 22
* Subsection: 8
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [ ] Linux (Other)
  - [x] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [x] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

## Description 

When the book refers to a model field, the convention used is not explicit when passing arguments like the verbose_name, the explanation for this is not easy to find in the Django Documentation, it took me some time to find out it was the verbose_name:

```
class User(AbstractUser):
    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )
```

I have not finished the book yet but this happens in every section that refers to the models fields being used 

# Possible Solutions

By using explicit declaration on the arguments, we as readers we will be able to get a better understanding of why that string is being passed to the model field:

```
class User(AbstractUser):
    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        verbose_name=_("Name of User"), blank=True, max_length=255
    )
```

## Your full name so we can provide accurate credit within the book

Elvio Severino (he_saw)

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
