### ISSUE TITLE
Figure 45 and Figure 46 are swapped

### ISSUE THREAD

**Issue by Delvio** [feldroy/django-crash-course#347]
## Location within the Book

* Book build date (Is the date on page 1): 2020-07-29
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: II
* Section: 46
* Subsection: 5
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [ ] Linux (Other)
  - [x] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [x] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

## Description 

FIgure 45 shows the "Cheese Add Form" screen while the figure 46 shows the Django Debug error for the "No URL to Redirect To" that is referenced in section 46.4

## Possible Solutions

Swap the images, what is showing on figure 46 should show up on the section 46.4 and what shows on Figure 45 should show where the Figure 46 is. 

## Your full name so we can provide accurate credit within the book

Elvio Severino

**Comment by thorrak** [comment]
This issue also appears in the 2020-08-21 version of the book PDF. 

I don't think that swapping the images will solve the problem - I think the tags to bring in the figures are potentially in the wrong spot. 

- Figure 45 shows up in 46.6 but the text referencing the figure is `We should now see the Add Cheese form:` early in 46.5. 
- Figure 46 shows up later in 46.6, but the text referencing the figure is `Be forewarned as we're going to generate an error page:` at the end of 46.5.


**Separately** I think Figure 45 is referencing a different version of the EveryCheese app. My version doesn't have the nice, cheesy logo.

**Comment by pydanny** [comment]
🚢 🧀
