### ISSUE TITLE
Chapter 53 : Cannot find a reference 'assertContains' in asserts.py

### ISSUE THREAD

**Issue by face1337** [feldroy/django-crash-course#348]
* Book build date (Is the date on page 1): 2020-03-10
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 53
* Section:53.2
* What operating system are you using:
  -  Windows 10 Home, Version 1909 or lower

> Hello, I am having a problem in chapter nr 53. So, when i try to run the tests i get an error : 
`=============================================================================== short test summary info ===============================================================================
FAILED everycheese/cheeses/tests/test_views.py::test_good_cheese_list_view_expanded - AttributeError: 'function' object has no attribute 'status_code'
FAILED everycheese/cheeses/tests/test_views.py::test_good_cheese_list_view - AssertionError: False is not true : Couldn't find 'Cheese List' in response

Results (2.85s):
      11 passed
       2 failed
         - everycheese\cheeses\tests/test_views.py:20 test_good_cheese_list_view_expanded
         - everycheese\cheeses\tests/test_views.py:42 test_good_cheese_list_view
Can't add file tracer data for unmeasured file 'C:\Users\Tomek\Desktop\django_projects\everycheese\everycheese\templates\cheeses\cheese_list.html'
`

>Here is the code. PyCharm highlights me an error when i import assertContains or assertRedirects. I don't know why is this happening..

```
import pytest
from pytest_django.asserts import assertContains, assertRedirects
from django.urls import reverse
from django.contrib.sessions.middleware \
    import SessionMiddleware
from django.test import RequestFactory

from everycheese.users.models import User
from ..models import Cheese
from ..views import (
    CheeseCreateView,
    CheeseDetailView,
    CheeseListView
)
from .factories import CheeseFactory

pytestmark = pytest.mark.django_db


def test_good_cheese_list_view_expanded(rf):
    # Determine URL
    url = reverse("cheeses:list")
    """
    rf is pytest shortcut to django.test.RequestFactory
    We generate a request as if from a user accesing the cheese list view
    """
    request = rf.get(url)
    # call 'as_view()' to make a callable object
    # callable_obj is analogus to function_based_view
    callable_obj = CheeseListView.as_view()
    """
    Pass in the request into the callable_obj to get an
    HTTP response served up by django
    """
    response = callable_obj
    """
    test that HTTP response has 'Cheese List' in the HTML and has a 200 response code
    """
    assertContains(response, 'Cheese List')


def test_good_cheese_list_view(rf):
    # Get the reauest
    request = rf.get(reverse("cheeses:list"))
    # Use the request to get the response
    response = CheeseListView.as_view()(request)
    # Test that the response is valid
    assertContains(response, 'Cheese List')



```

Thanks for help in advance/

**Comment by pydanny** [comment]
Your version is months out of date. This was fixed months ago. Had you purchased the book, you would be working with a current version. Please purchase the book, this little girl eats off the proceeds of this book. 
![Uploading uma.jpg…]()
