### ISSUE TITLE
9.1: Mention pathlib.Path

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#351]
## Location within the Book

* Book build date (Is the date on page 1): 2020-08-21
* Book format (PDF, Epub or Mobi): 
* Chapter or Appendix: 9
* Section: 1
* Subsection:
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [X] Linux (Other)
  - [ ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

 In order to specify where we want Django to look for templates, the book states:

> Go ahead and modify that slightly, by adding `BASE_DIR / "templates"`, to the `DIRS` list on the fourth line.
> ...
> `'DIRS': [BASE_DIR / "templates", ],`

As `pathlib.Path` is a relatively new feature, probably many readers would expect the use of `os.path.join()` and be somewhat confused about how this could possibly work on MS Windows.

## Possible Solutions

Briefly discuss `pathlib.Path`.

## Your full name so we can provide accurate credit within the book

Enrique Matías Sánchez

**Comment by pydanny** [comment]
🚢 🧀
