### ISSUE TITLE
15.3: Grammar

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#352]
## Location within the Book

* Book build date (Is the date on page 1): 2020-08-21
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 15
* Section: 3
* Subsection:
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [X] Linux (Other)
  - [ ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> Create a new Conda environment called `everycheese` **configure it** to use python3.8:

## Possible Solutions

Create a new Conda environment called `everycheese` and configure it to use Python 3.8:
or
Create a new Conda environment called `everycheese` configuring it to use Python 3.8:

## Your full name so we can provide accurate credit within the book

Enrique Matías Sánchez

**Comment by Scarletbegonias68** [comment]
Thank you again!
