### ISSUE TITLE
20.4.2: Grammar

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#353]
## Location within the Book

* Book build date (Is the date on page 1): 2020-08-21
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 20
* Section: 4
* Subsection: 2
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [X] Linux (Other)
  - [ ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> We should in the root of the `everycheese/` directory structure.

## Possible Solutions

We should **be** in the root of the `everycheese/` directory structure.

## Your full name so we can provide accurate credit within the book

Enrique Matías Sánchez

**Comment by Scarletbegonias68** [comment]
And again, thank you!
