### ISSUE TITLE
Ability to highlight text and make comments in Apple Preview

### ISSUE THREAD

**Issue by jtmdk** [feldroy/django-crash-course#354]
## Location within the Book

* Book build date (Is the date on page 1): 2020-08-21
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: (applies to document in general)
* Section:
* Subsection:
* What operating system are you using:
  - [x] MacOS Catalina

## Description 

I am using the PDF version in the Preview program on my MacBook. When I highlight text (to make note of something), When I highlight text in Preview, it automatically creates a copy of the PDF file and gives a notification: 'The original document can’t be changed, so a duplicate with your changes has been created.' This copy cannot be saved in Preview. I have used this feature in PDF versions of books by William Vincent (https://learndjango.com/books/) and this is not an issue with these books.

<img width="740" alt="Screen Shot 2020-08-29 at 08 57 45" src="https://user-images.githubusercontent.com/63544383/91630904-bad44200-e9d5-11ea-83fa-060f4c589d49.png">

## Possible Solutions

It would be great if I can use highlighted and notes feature in the PDF version of this book.

## Your full name so we can provide accurate credit within the book

Joel Thomas Mulligan

**Comment by pydanny** [comment]
We've spent a lot of time analyzing our current build process components, specifically bookdown and PyPDF2. We can't figure out how to make this work for ourselves, much less others.

The answer is to move to another build process, something that will take significantly more time than what we have. This is something we will be doing for the 4.x edition of the book, which won't come out for at least a year. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
