### ISSUE TITLE
Can you provide link to TODO command line tutorial?

### ISSUE THREAD

**Issue by jtmdk** [feldroy/django-crash-course#355]
## Location within the Book

* Book build date (Is the date on page 1): 2020-08-21
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 1
* Section: 1.1
* Subsection:
* What operating system are you using:
  - [x] MacOS Catalina

## Description 

With reference to text 'work through a command line tutorial such as TODO.' Can you provide a link to this specific tutorial as it is not clear which specific tutorial you are refering to.

## Your full name so we can provide accurate credit within the book

Joel Thomas Mulligan

**Comment by pydanny** [comment]
Thank you for submitting this issue. However, per our issue template, reporting TODOs isn't counted as an attributable item.
