### ISSUE TITLE
20.4.2 Add Our Files: "git status" may help new users here

### ISSUE THREAD

**Issue by mark-sevelj** [feldroy/django-crash-course#356]
## Location within the Book

* Book build date (Is the date on page 1): 2020-08-21
* Book format (PDF, Epub or Mobi):  PDF
* Chapter or Appendix: 18
* Section: 4
* Subsection: 2 Add Our Files
* What operating system are you using:
  - [ x] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [ ] Linux (Other)
  - [ ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 
It may helpful to those new to git to use "git status" to see changes before/after "git add ."

## Possible Solutions
Add a "git status" before and after the "git add ." command with a very brief explanation of results.

## Your full name so we can provide accurate credit within the book
Mark Sevelj

**Comment by pydanny** [comment]
Hey! As much as we like your suggestion, we want to focus this edition of Django Crash Course on being as concise as possible. It is definitely something we'll consider for a future Django 4.x version of this book. Therefore, we're going to be labeling this issue as a `4.x suggestion` and closing it for now.
