### ISSUE TITLE
RuntimeError: Model class everycheese

### ISSUE THREAD

**Issue by Ah8Huang** [feldroy/django-crash-course#360]
Hi, everyone,
I have a problem and I hope you could help me.

C:\Users\hxd66\projects\everycheese\everycheese\cheeses\models.py  runs as:
from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel

class Cheese(TimeStampedModel):
    class Firmness(models.TextChoices):
          UNSPECIFIED = "unspecified", "Unspecified"
          SOFT = "soft", "Soft"
          SEMI_SOFT = "semi-soft", "Semi-Soft"
          SEMI_HARD ="semi-hard", "Semi-Hard"
          HARD = "hard", "Hard"
    
    name = models.CharField("Name of Cheese", max_length=255)
    slug = AutoSlugField("Cheese Address",
          unique=True, always_update=False, populate_from="name")
    description = models.TextField("Description", blank=True)

    firmness = models.CharField("Firmness", max_length=20, 
        choices=Firmness.choices, default=Firmness.UNSPECIFIED,
    )    
    def __str__(self):
        return self.name

In C:\Users\hxd66\projects\everycheese\config\settings\base.py, it has:
...
LOCAL_APPS = [
    "everycheese.users.apps.UsersConfig",   
    'everycheese.cheeses.apps.CheesesConfig', 
]
**INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS**
.....
When I run  **python manage.py makemigrations**  I got an error:
"RuntimeError: Model class everycheese.cheeses.models.Cheese doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS."

Any good idea to fix it/

**Comment by pydanny** [comment]
Apologies, but we can only afford to support those customers who have purchased the book. We cannot find your name in our system. Please purchase the book and we will be able to provide assistance.
