### ISSUE TITLE
Section 1.3 - Claiming that Visual Studio Code linked to in the book is Open Source, is false

### ISSUE THREAD

**Issue by cseder** [feldroy/django-crash-course#361]
## Location within the Book

* Book order number: 57098080
* Book build date (Is the date on page 1): 2020-09-08
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 1
* Section: 3
* Subsection: 1
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [x] Linux (Other)
  - [x] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

There is a common misconception that VS Code is Open Source. **This is NOT correct**.
It is (according to official Microsoft statements) *"based on"* the open source code available on Github.

But no mention is given regarding the pre-compiled binaries you link to in the book. 
These actually includes several proprietary, not documented with source or otherwise, tracking and telemetry 
functionality that isn't part of the Github open source code. 
VS Code doesn't even compile "out of the box" using that code.

**So, please, don't spread this misinformation more than has already been done by multiple known developers in various books and on many forums and blogs around on the web.**

## Possible Solutions

Don't mention Open Source AT ALL when talking about Visual Studio Code or linking to the binary installers / executables delivered by Microsoft. 
That is Visual Studio Code or "Code" for short. This is in fact a different end-product from the Github source code,
even if it does *include* that code.

If you want to give readers an alternative, please mention that it is possible to download and install versions of @VSCodium that actually IS open source. 
A version of VS Code without the spyware and other proprietary components. Microsoft's "Marketplace" that hosts all the plugins is also closed source and proprietary code, so VSCodium uses [Open VSX](https://open-vsx.org) for its plugins, and this IS open source.

## Your full name so we can provide accurate credit within the book
Chris Sederqvst

**Comment by pydanny** [comment]
Resolved already. Thanks Chris!
