### ISSUE TITLE
9.1: Markdown syntax error

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#362]
## Location within the Book

* Book order number: 
* Book build date (Is the date on page 1): 2020-09-08
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: 9
* Section: 2 and 3 
* Subsection:
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [X] Linux (Other)
  - [ ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

It seems there is a syntax problem in the markdown code, probably at the end of section 9.1.
Sections 9.2 and 9.3 appears in the PDF as uninterpreted markdown source code.

## Possible Solutions

Check the markdown code at the end of section 9.1 ("Configure Your Templates")

## Your full name so we can provide accurate credit within the book

Enrique Matías Sánchez (Quique)

**Comment by pydanny** [comment]
🚢 🧀
