### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sspaek** [feldroy/django-crash-course#365]
## Location within the Book

* Book order number: 9312
* Book build date (Is the date on page 1): Sept 16 2020
* Book format (PDF, Epub or Mobi): PDF
* Chapter or Appendix: Ch 25 Running tests
* Section:2
* Subsection:
* What operating system are you using:
  - [ ] Linux (Ubuntu 20.04)
  - [ ] Linux (Ubuntu 18.04)
  - [ ] Linux (Other)
  - [x ] MacOS Catalina
  - [ ] MacOS Mojave
  - [ ] MacOS Big Sur
  - [ ] Windows 10 Pro, Version 2004 or higher
  - [ ] Windows 10 Pro, Version 1909 or lower
  - [ ] Windows 10 Home, Version 2004 or higher
  - [ ] Windows 10 Home, Version 1909 or lower

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> If grammar, enter problematic text here, otherwise delete this line.

```
coverage run -m pytest

E               psycopg2.errors.InsufficientPrivilege: permission denied for table django_migrations

/opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/db/backends/utils.py:84: InsufficientPrivilege

```

**Comment by luzfcb** [comment]
@sspaek Thanks for reporting an issue.

How you installed PostgreSQL? Did you install it via https://postgresapp.com/?

**Comment by sspaek** [comment]
Thanks for your help. It's probably some basic setup with postgres, but I've got no experience setting by DBs. I followed instructions in 1.6.2 Installing PostgreSQL on Mac. Everything else in the book has been very easy to follow.

**Comment by luzfcb** [comment]
Did you run the commands of chapter 18, especially the commands of 18.3.1 and 18.4.1 chapter?

**Comment by sspaek** [comment]
yes, i checked again and .env shows `DATABASE_URL=postgres://myuser:mypasswd@localhost:5432/everycheese
`
when i tried creating DB with `python manage.py sqlcreate | psql` it complained that DB already existed. so i did a DROP database first and then the command worked.

**Comment by luzfcb** [comment]
@sspaek Do you still have problems or is already solved?

**Comment by sspaek** [comment]
Nothing is solved. I have not made any changes after opening this issue

**Comment by sspaek** [comment]
`                                                                                                               100% ██████████
================================================== short test summary info ===================================================
FAILED everycheese/users/tests/test_forms.py::TestUserCreationForm::test_clean_username - django.db.utils.ProgrammingError:...
FAILED everycheese/users/tests/test_models.py::test_user_get_absolute_url - django.db.utils.ProgrammingError: permission de...
FAILED everycheese/users/tests/test_urls.py::test_detail - django.db.utils.ProgrammingError: permission denied for table dj...
FAILED everycheese/users/tests/test_urls.py::test_update - django.db.utils.ProgrammingError: permission denied for table dj...
FAILED everycheese/users/tests/test_urls.py::test_redirect - django.db.utils.ProgrammingError: permission denied for table ...
FAILED everycheese/users/tests/test_views.py::TestUserUpdateView::test_get_success_url - django.db.utils.ProgrammingError: ...
FAILED everycheese/users/tests/test_views.py::TestUserUpdateView::test_get_object - django.db.utils.ProgrammingError: permi...
FAILED everycheese/users/tests/test_views.py::TestUserUpdateView::test_form_valid - django.db.utils.ProgrammingError: permi...
FAILED everycheese/users/tests/test_views.py::TestUserRedirectView::test_get_redirect_url - django.db.utils.ProgrammingErro...

Results (3.99s):
       9 error`

**Comment by luzfcb** [comment]
@sspaek can you please, replace `myuser` by `myuser2` on the `.env` file and run the command of chapter 18.4.1 again, and then run `coverage run -m pytest`

**Comment by sspaek** [comment]
DATABASE_URL=postgres://myuser2:mypasswd@localhost:5432/everycheese

Changed to `myuser2` but I still have the same errors.

**Comment by sspaek** [comment]
works now, thanks fabio

**Comment by luzfcb** [comment]
@sspaek What did you do to get the issue fixed?

**Comment by sspaek** [comment]
i think i had issues because i had created a DB earlier. I uninstalled postgresql and re-installed, and also followed your instruction to change myuser and myuser2. Thanks again for your help.
