### ISSUE TITLE
1. Command line tutorials

### ISSUE THREAD

**Issue by quique** [feldroy/django-crash-course#64]
## Location within the Book

* Chapter or Appendix: 1. The Ultimate Django Setup
* Section: Goal: A Professional-Quality Development Environment
* Subsection:

## Description 

>  Are comfortable using the command line. If not, work through a command line tutorial such as TODO.

Even though TODOs do not qualify as attributable items, I'll provide a couple of suggestions:

* <https://ubuntu.com/tutorials/command-line-for-beginners>
* <http://linuxcommand.org/lc3_learning_the_shell.php>
* For serious learners, _The Linux Command Line_ by William Shotts is excellent, and
  it is freely available for download at <http://linuxcommand.org/tlcl.php>

**Comment by pydanny** [comment]
While those are three good links, I think a more general command-line tutorial would be more ideal. Those are specific to Linux, and we want something that's more general.
