### ISSUE TITLE
36. Light Theme vs. Dark Theme for navbar

### ISSUE THREAD

**Issue by SmartC2016** [feldroy/django-crash-course#78]
## Location within the Book

* Chapter or Appendix: 36
* Section: 3
* Subsection:

I have actually just noticed now.

The theme for the navbar in the code is light, where the theme of the navbar in the screenshots is dark.

I checked the ```base.html``` in the ```templates``` directory.

Indeed there is the line:
```
<nav class="navbar navbar-expand-md navbar-light bg-light">
```

I guess it should be
```
<nav class="navbar navbar-expand-md navbar-light bg-dark">
```

to match the screenshots. I suppose you need to change the font-color then as well.

**Comment by pydanny** [comment]
@luzfcb Most of the dark themed images are in the `unvalidated\` directory. I haven't had bandwidth to retake them and move them to the `images\` directory.

**Comment by pydanny** [comment]
Just read the original issue carefully and implemented it as dark. Thank you @SmartC2016!
